INSERT INTO public.stickers (number, name, section, sticker_type) VALUES
(1, 'Lámina 1', 'Intro', 'normal'),
(2, 'Lámina 2', 'Intro', 'shiny'),
(3, 'Lámina 3', 'Intro', 'normal'),
(4, 'Lámina 4', 'Intro', 'special'),
(5, 'Lámina 5', 'Intro', 'normal'),
(6, 'Lámina 6', 'Intro', 'normal'),
(7, 'Lámina 7', 'Intro', 'shiny'),
(8, 'Lámina 8', 'Intro', 'normal'),
(9, 'Lámina 9', 'Intro', 'special'),
(10, 'Lámina 10', 'Intro', 'normal'),
(11, 'Lámina 11', 'Estadios', 'normal'),
(12, 'Lámina 12', 'Estadios', 'shiny'),
(13, 'Lámina 13', 'Estadios', 'normal'),
(14, 'Lámina 14', 'Estadios', 'special'),
(15, 'Lámina 15', 'Estadios', 'normal'),
(16, 'Lámina 16', 'Estadios', 'normal'),
(17, 'Lámina 17', 'Estadios', 'shiny'),
(18, 'Lámina 18', 'Estadios', 'normal'),
(19, 'Lámina 19', 'Mascotas', 'special'),
(20, 'Lámina 20', 'Mascotas', 'normal'),
(21, 'Lámina 21', 'Mascotas', 'normal'),
(22, 'Lámina 22', 'Mascotas', 'shiny'),
(23, 'Lámina 23', 'Mascotas', 'normal'),
(24, 'Lámina 24', 'Mascotas', 'special'),
(25, 'Lámina 25', 'Equipos Grupo A', 'normal'),
(26, 'Lámina 26', 'Equipos Grupo A', 'normal'),
(27, 'Lámina 27', 'Equipos Grupo A', 'shiny'),
(28, 'Lámina 28', 'Equipos Grupo A', 'normal'),
(29, 'Lámina 29', 'Equipos Grupo A', 'special'),
(30, 'Lámina 30', 'Equipos Grupo A', 'normal'),
(31, 'Lámina 31', 'Equipos Grupo A', 'normal'),
(32, 'Lámina 32', 'Equipos Grupo A', 'shiny'),
(33, 'Lámina 33', 'Equipos Grupo A', 'normal'),
(34, 'Lámina 34', 'Equipos Grupo A', 'special'),
(35, 'Lámina 35', 'Equipos Grupo A', 'normal'),
(36, 'Lámina 36', 'Equipos Grupo A', 'normal'),
(37, 'Lámina 37', 'Equipos Grupo B', 'shiny'),
(38, 'Lámina 38', 'Equipos Grupo B', 'normal'),
(39, 'Lámina 39', 'Equipos Grupo B', 'special'),
(40, 'Lámina 40', 'Equipos Grupo B', 'normal'),
(41, 'Lámina 41', 'Equipos Grupo B', 'normal'),
(42, 'Lámina 42', 'Equipos Grupo B', 'shiny'),
(43, 'Lámina 43', 'Equipos Grupo B', 'normal'),
(44, 'Lámina 44', 'Equipos Grupo B', 'special'),
(45, 'Lámina 45', 'Equipos Grupo B', 'normal'),
(46, 'Lámina 46', 'Equipos Grupo B', 'normal'),
(47, 'Lámina 47', 'Equipos Grupo B', 'shiny'),
(48, 'Lámina 48', 'Equipos Grupo B', 'normal'),
(49, 'Lámina 49', 'Equipos Grupo C', 'special'),
(50, 'Lámina 50', 'Equipos Grupo C', 'normal'),
(51, 'Lámina 51', 'Equipos Grupo C', 'normal'),
(52, 'Lámina 52', 'Equipos Grupo C', 'shiny'),
(53, 'Lámina 53', 'Equipos Grupo C', 'normal'),
(54, 'Lámina 54', 'Equipos Grupo C', 'special'),
(55, 'Lámina 55', 'Equipos Grupo C', 'normal'),
(56, 'Lámina 56', 'Equipos Grupo C', 'normal'),
(57, 'Lámina 57', 'Equipos Grupo C', 'shiny'),
(58, 'Lámina 58', 'Equipos Grupo C', 'normal'),
(59, 'Lámina 59', 'Equipos Grupo C', 'special'),
(60, 'Lámina 60', 'Equipos Grupo C', 'normal'),
(61, 'Lámina 61', 'Equipos Grupo D', 'normal'),
(62, 'Lámina 62', 'Equipos Grupo D', 'shiny'),
(63, 'Lámina 63', 'Equipos Grupo D', 'normal'),
(64, 'Lámina 64', 'Equipos Grupo D', 'special'),
(65, 'Lámina 65', 'Equipos Grupo D', 'normal'),
(66, 'Lámina 66', 'Equipos Grupo D', 'normal'),
(67, 'Lámina 67', 'Equipos Grupo D', 'shiny'),
(68, 'Lámina 68', 'Equipos Grupo D', 'normal'),
(69, 'Lámina 69', 'Equipos Grupo D', 'special'),
(70, 'Lámina 70', 'Equipos Grupo D', 'normal'),
(71, 'Lámina 71', 'Equipos Grupo D', 'normal'),
(72, 'Lámina 72', 'Equipos Grupo D', 'shiny'),
(73, 'Lámina 73', 'Leyendas', 'normal'),
(74, 'Lámina 74', 'Leyendas', 'special'),
(75, 'Lámina 75', 'Leyendas', 'normal'),
(76, 'Lámina 76', 'Leyendas', 'normal'),
(77, 'Lámina 77', 'Leyendas', 'shiny'),
(78, 'Lámina 78', 'Leyendas', 'normal'),
(79, 'Lámina 79', 'Leyendas', 'special'),
(80, 'Lámina 80', 'Leyendas', 'normal'),
(81, 'Lámina 81', 'Leyendas', 'normal'),
(82, 'Lámina 82', 'Leyendas', 'shiny'),
(83, 'Lámina 83', 'Finales', 'normal'),
(84, 'Lámina 84', 'Finales', 'special'),
(85, 'Lámina 85', 'Finales', 'normal'),
(86, 'Lámina 86', 'Finales', 'normal'),
(87, 'Lámina 87', 'Finales', 'shiny'),
(88, 'Lámina 88', 'Finales', 'normal'),
(89, 'Lámina 89', 'Finales', 'special'),
(90, 'Lámina 90', 'Finales', 'normal')
ON CONFLICT (number) DO NOTHING;
