INSERT INTO public.stickers (number, code, name, section, team_code, team_name, team_slot, sticker_kind, sticker_type, display_order) VALUES
(1, 'FWC1', 'Emblema oficial', 'FWC', 'FWC', 'FIFA World Cup', 1, 'fwc', 'special', 0),
(2, 'FWC2', 'Trofeo FIFA', 'FWC', 'FWC', 'FIFA World Cup', 2, 'fwc', 'shiny', 1),
(3, 'FWC3', 'Mascota del torneo', 'FWC', 'FWC', 'FIFA World Cup', 3, 'fwc', 'normal', 2),
(4, 'FWC4', 'Póster del Mundial', 'FWC', 'FWC', 'FIFA World Cup', 4, 'fwc', 'normal', 3),
(5, 'FWC5', 'Historia FWC 1', 'FWC', 'FWC', 'FIFA World Cup', 5, 'fwc', 'normal', 4),
(6, 'FWC6', 'Historia FWC 2', 'FWC', 'FWC', 'FIFA World Cup', 6, 'fwc', 'normal', 5),
(7, 'FWC7', 'México sede', 'FWC', 'FWC', 'FIFA World Cup', 7, 'fwc', 'shiny', 6),
(8, 'FWC8', 'Estadio Ciudad de México', 'FWC', 'FWC', 'FIFA World Cup', 8, 'fwc', 'normal', 7),
(9, 'FWC9', 'Estadio Guadalajara', 'FWC', 'FWC', 'FIFA World Cup', 9, 'fwc', 'normal', 8),
(10, 'FWC10', 'Estadio Monterrey', 'FWC', 'FWC', 'FIFA World Cup', 10, 'fwc', 'normal', 9),
(11, 'FWC11', 'USA sede', 'FWC', 'FWC', 'FIFA World Cup', 11, 'fwc', 'normal', 10),
(12, 'FWC12', 'Canadá sede', 'FWC', 'FWC', 'FIFA World Cup', 12, 'fwc', 'normal', 11),
(13, 'FWC13', 'FWC Leyenda 1', 'FWC', 'FWC', 'FIFA World Cup', 13, 'fwc', 'shiny', 12),
(14, 'FWC14', 'FWC Leyenda 2', 'FWC', 'FWC', 'FIFA World Cup', 14, 'fwc', 'normal', 13),
(15, 'FWC15', 'FWC Leyenda 3', 'FWC', 'FWC', 'FIFA World Cup', 15, 'fwc', 'normal', 14),
(16, 'FWC16', 'FWC Leyenda 4', 'FWC', 'FWC', 'FIFA World Cup', 16, 'fwc', 'special', 15),
(17, 'FWC17', 'FWC Leyenda 5', 'FWC', 'FWC', 'FIFA World Cup', 17, 'fwc', 'normal', 16),
(18, 'FWC18', 'FWC Leyenda 6', 'FWC', 'FWC', 'FIFA World Cup', 18, 'fwc', 'normal', 17),
(19, 'FWC19', 'FWC Leyenda 7', 'FWC', 'FWC', 'FIFA World Cup', 19, 'fwc', 'shiny', 18),
(20, 'FWC20', 'FWC Leyenda 8', 'FWC', 'FWC', 'FIFA World Cup', 20, 'fwc', 'normal', 19),
(21, 'MEX1', 'Escudo México', 'México', 'MEX', 'México', 1, 'escudo', 'shiny', 20),
(22, 'MEX2', 'Luis Malagón', 'México', 'MEX', 'México', 2, 'jugador', 'normal', 21),
(23, 'MEX3', 'Johan Vásquez', 'México', 'MEX', 'México', 3, 'jugador', 'normal', 22),
(24, 'MEX4', 'Jorge Sánchez', 'México', 'MEX', 'México', 4, 'jugador', 'normal', 23),
(25, 'MEX5', 'César Montes', 'México', 'MEX', 'México', 5, 'jugador', 'normal', 24),
(26, 'MEX6', 'Jesús Gallardo', 'México', 'MEX', 'México', 6, 'jugador', 'normal', 25),
(27, 'MEX7', 'Israel Reyes', 'México', 'MEX', 'México', 7, 'jugador', 'normal', 26),
(28, 'MEX8', 'Diego Laínez', 'México', 'MEX', 'México', 8, 'jugador', 'normal', 27),
(29, 'MEX9', 'Carlos Rodríguez', 'México', 'MEX', 'México', 9, 'jugador', 'normal', 28),
(30, 'MEX10', 'Edson Álvarez', 'México', 'MEX', 'México', 10, 'jugador', 'shiny', 29),
(31, 'MEX11', 'Orbelín Pineda', 'México', 'MEX', 'México', 11, 'jugador', 'normal', 30),
(32, 'MEX12', 'Marcel Ruiz', 'México', 'MEX', 'México', 12, 'jugador', 'normal', 31),
(33, 'MEX13', 'Foto de equipo', 'México', 'MEX', 'México', 13, 'foto_equipo', 'special', 32),
(34, 'MEX14', 'Érick Sánchez', 'México', 'MEX', 'México', 14, 'jugador', 'normal', 33),
(35, 'MEX15', 'Hirving Lozano', 'México', 'MEX', 'México', 15, 'jugador', 'shiny', 34),
(36, 'MEX16', 'Santiago Giménez', 'México', 'MEX', 'México', 16, 'jugador', 'normal', 35),
(37, 'MEX17', 'Raúl Jiménez', 'México', 'MEX', 'México', 17, 'jugador', 'shiny', 36),
(38, 'MEX18', 'Alexis Vega', 'México', 'MEX', 'México', 18, 'jugador', 'normal', 37),
(39, 'MEX19', 'Roberto Alvarado', 'México', 'MEX', 'México', 19, 'jugador', 'normal', 38),
(40, 'MEX20', 'César Huerta', 'México', 'MEX', 'México', 20, 'jugador', 'normal', 39),
(41, 'KOR1', 'Escudo Corea del Sur', 'Corea del Sur', 'KOR', 'Corea del Sur', 1, 'escudo', 'shiny', 40),
(42, 'KOR2', 'Son Heung-min', 'Corea del Sur', 'KOR', 'Corea del Sur', 2, 'jugador', 'normal', 41),
(43, 'KOR3', 'Kim Min-jae', 'Corea del Sur', 'KOR', 'Corea del Sur', 3, 'jugador', 'normal', 42),
(44, 'KOR4', 'Lee Kang-in', 'Corea del Sur', 'KOR', 'Corea del Sur', 4, 'jugador', 'normal', 43),
(45, 'KOR5', 'Hwang Hee-chan', 'Corea del Sur', 'KOR', 'Corea del Sur', 5, 'jugador', 'normal', 44),
(46, 'KOR6', 'Cho Gue-sung', 'Corea del Sur', 'KOR', 'Corea del Sur', 6, 'jugador', 'normal', 45),
(47, 'KOR7', 'Jung Woo-young', 'Corea del Sur', 'KOR', 'Corea del Sur', 7, 'jugador', 'normal', 46),
(48, 'KOR8', 'Hwang In-beom', 'Corea del Sur', 'KOR', 'Corea del Sur', 8, 'jugador', 'normal', 47),
(49, 'KOR9', 'Hong Hyun-seok', 'Corea del Sur', 'KOR', 'Corea del Sur', 9, 'jugador', 'normal', 48),
(50, 'KOR10', 'Kim Young-gwon', 'Corea del Sur', 'KOR', 'Corea del Sur', 10, 'jugador', 'shiny', 49),
(51, 'KOR11', 'Jo Hyeon-woo', 'Corea del Sur', 'KOR', 'Corea del Sur', 11, 'jugador', 'normal', 50),
(52, 'KOR12', 'Na Sang-ho', 'Corea del Sur', 'KOR', 'Corea del Sur', 12, 'jugador', 'normal', 51),
(53, 'KOR13', 'Foto de equipo', 'Corea del Sur', 'KOR', 'Corea del Sur', 13, 'foto_equipo', 'special', 52),
(54, 'KOR14', 'Paik Seung-ho', 'Corea del Sur', 'KOR', 'Corea del Sur', 14, 'jugador', 'normal', 53),
(55, 'KOR15', 'Yang Hyun-jun', 'Corea del Sur', 'KOR', 'Corea del Sur', 15, 'jugador', 'shiny', 54),
(56, 'KOR16', 'Kim Seung-gyu', 'Corea del Sur', 'KOR', 'Corea del Sur', 16, 'jugador', 'normal', 55),
(57, 'KOR17', 'Kim Jin-su', 'Corea del Sur', 'KOR', 'Corea del Sur', 17, 'jugador', 'shiny', 56),
(58, 'KOR18', 'Song Min-kyu', 'Corea del Sur', 'KOR', 'Corea del Sur', 18, 'jugador', 'normal', 57),
(59, 'KOR19', 'Lee Jae-sung', 'Corea del Sur', 'KOR', 'Corea del Sur', 19, 'jugador', 'normal', 58),
(60, 'KOR20', 'Hong Soo-hyun', 'Corea del Sur', 'KOR', 'Corea del Sur', 20, 'jugador', 'normal', 59),
(61, 'RSA1', 'Escudo Sudáfrica', 'Sudáfrica', 'RSA', 'Sudáfrica', 1, 'escudo', 'shiny', 60),
(62, 'RSA2', 'Ronwen Williams', 'Sudáfrica', 'RSA', 'Sudáfrica', 2, 'jugador', 'normal', 61),
(63, 'RSA3', 'Grant Kekana', 'Sudáfrica', 'RSA', 'Sudáfrica', 3, 'jugador', 'normal', 62),
(64, 'RSA4', 'Teboho Mokoena', 'Sudáfrica', 'RSA', 'Sudáfrica', 4, 'jugador', 'normal', 63),
(65, 'RSA5', 'Khuliso Mudau', 'Sudáfrica', 'RSA', 'Sudáfrica', 5, 'jugador', 'normal', 64),
(66, 'RSA6', 'Mothobi Mvala', 'Sudáfrica', 'RSA', 'Sudáfrica', 6, 'jugador', 'normal', 65),
(67, 'RSA7', 'Teboho Mokwena', 'Sudáfrica', 'RSA', 'Sudáfrica', 7, 'jugador', 'normal', 66),
(68, 'RSA8', 'Sphelele Mkhulise', 'Sudáfrica', 'RSA', 'Sudáfrica', 8, 'jugador', 'normal', 67),
(69, 'RSA9', 'Thapelo Maseko', 'Sudáfrica', 'RSA', 'Sudáfrica', 9, 'jugador', 'normal', 68),
(70, 'RSA10', 'Sphelele Ntubeni', 'Sudáfrica', 'RSA', 'Sudáfrica', 10, 'jugador', 'shiny', 69),
(71, 'RSA11', 'Themba Zwane', 'Sudáfrica', 'RSA', 'Sudáfrica', 11, 'jugador', 'normal', 70),
(72, 'RSA12', 'Percy Tau', 'Sudáfrica', 'RSA', 'Sudáfrica', 12, 'jugador', 'normal', 71),
(73, 'RSA13', 'Foto de equipo', 'Sudáfrica', 'RSA', 'Sudáfrica', 13, 'foto_equipo', 'special', 72),
(74, 'RSA14', 'Evidence Makgopa', 'Sudáfrica', 'RSA', 'Sudáfrica', 14, 'jugador', 'normal', 73),
(75, 'RSA15', 'Zakhele Lepasa', 'Sudáfrica', 'RSA', 'Sudáfrica', 15, 'jugador', 'shiny', 74),
(76, 'RSA16', 'Tebogo Maseko', 'Sudáfrica', 'RSA', 'Sudáfrica', 16, 'jugador', 'normal', 75),
(77, 'RSA17', 'Mihlali Mayambela', 'Sudáfrica', 'RSA', 'Sudáfrica', 17, 'jugador', 'shiny', 76),
(78, 'RSA18', 'Oswin Appollis', 'Sudáfrica', 'RSA', 'Sudáfrica', 18, 'jugador', 'normal', 77),
(79, 'RSA19', 'Thapelo Leshabane', 'Sudáfrica', 'RSA', 'Sudáfrica', 19, 'jugador', 'normal', 78),
(80, 'RSA20', 'Iqraam Rayners', 'Sudáfrica', 'RSA', 'Sudáfrica', 20, 'jugador', 'normal', 79),
(81, 'CZE1', 'Escudo Chequia', 'Chequia', 'CZE', 'Chequia', 1, 'escudo', 'shiny', 80),
(82, 'CZE2', 'Tomáš Vaclík', 'Chequia', 'CZE', 'Chequia', 2, 'jugador', 'normal', 81),
(83, 'CZE3', 'Vladimír Coufal', 'Chequia', 'CZE', 'Chequia', 3, 'jugador', 'normal', 82),
(84, 'CZE4', 'Tomáš Souček', 'Chequia', 'CZE', 'Chequia', 4, 'jugador', 'normal', 83),
(85, 'CZE5', 'Patrik Schick', 'Chequia', 'CZE', 'Chequia', 5, 'jugador', 'normal', 84),
(86, 'CZE6', 'Antonín Barák', 'Chequia', 'CZE', 'Chequia', 6, 'jugador', 'normal', 85),
(87, 'CZE7', 'Milan Havel', 'Chequia', 'CZE', 'Chequia', 7, 'jugador', 'normal', 86),
(88, 'CZE8', 'David Doudera', 'Chequia', 'CZE', 'Chequia', 8, 'jugador', 'normal', 87),
(89, 'CZE9', 'Ondřej Lingr', 'Chequia', 'CZE', 'Chequia', 9, 'jugador', 'normal', 88),
(90, 'CZE10', 'Adam Hložek', 'Chequia', 'CZE', 'Chequia', 10, 'jugador', 'shiny', 89),
(91, 'CZE11', 'Ladislav Krejčí', 'Chequia', 'CZE', 'Chequia', 11, 'jugador', 'normal', 90),
(92, 'CZE12', 'Robin Hranáč', 'Chequia', 'CZE', 'Chequia', 12, 'jugador', 'normal', 91),
(93, 'CZE13', 'Foto de equipo', 'Chequia', 'CZE', 'Chequia', 13, 'foto_equipo', 'special', 92),
(94, 'CZE14', 'Tomáš Holeš', 'Chequia', 'CZE', 'Chequia', 14, 'jugador', 'normal', 93),
(95, 'CZE15', 'Jaroslav Zelený', 'Chequia', 'CZE', 'Chequia', 15, 'jugador', 'shiny', 94),
(96, 'CZE16', 'Michal Sadílek', 'Chequia', 'CZE', 'Chequia', 16, 'jugador', 'normal', 95),
(97, 'CZE17', 'Matěj Jurasek', 'Chequia', 'CZE', 'Chequia', 17, 'jugador', 'shiny', 96),
(98, 'CZE18', 'Vladimír Darida', 'Chequia', 'CZE', 'Chequia', 18, 'jugador', 'normal', 97),
(99, 'CZE19', 'Pavel Šulc', 'Chequia', 'CZE', 'Chequia', 19, 'jugador', 'normal', 98),
(100, 'CZE20', 'Jiří Pavlenka', 'Chequia', 'CZE', 'Chequia', 20, 'jugador', 'normal', 99),
(101, 'CAN1', 'Escudo Canadá', 'Canadá', 'CAN', 'Canadá', 1, 'escudo', 'shiny', 100),
(102, 'CAN2', 'Maxime Crépeau', 'Canadá', 'CAN', 'Canadá', 2, 'jugador', 'normal', 101),
(103, 'CAN3', 'Alphonso Davies', 'Canadá', 'CAN', 'Canadá', 3, 'jugador', 'normal', 102),
(104, 'CAN4', 'Steven Vitoria', 'Canadá', 'CAN', 'Canadá', 4, 'jugador', 'normal', 103),
(105, 'CAN5', 'Sam Adekugbe', 'Canadá', 'CAN', 'Canadá', 5, 'jugador', 'normal', 104),
(106, 'CAN6', 'Derek Cornelius', 'Canadá', 'CAN', 'Canadá', 6, 'jugador', 'normal', 105),
(107, 'CAN7', 'Richie Laryea', 'Canadá', 'CAN', 'Canadá', 7, 'jugador', 'normal', 106),
(108, 'CAN8', 'Sam Piette', 'Canadá', 'CAN', 'Canadá', 8, 'jugador', 'normal', 107),
(109, 'CAN9', 'Stephen Eustáquio', 'Canadá', 'CAN', 'Canadá', 9, 'jugador', 'normal', 108),
(110, 'CAN10', 'Jonathan David', 'Canadá', 'CAN', 'Canadá', 10, 'jugador', 'shiny', 109),
(111, 'CAN11', 'Liam Millar', 'Canadá', 'CAN', 'Canadá', 11, 'jugador', 'normal', 110),
(112, 'CAN12', 'Tajon Buchanan', 'Canadá', 'CAN', 'Canadá', 12, 'jugador', 'normal', 111),
(113, 'CAN13', 'Foto de equipo', 'Canadá', 'CAN', 'Canadá', 13, 'foto_equipo', 'special', 112),
(114, 'CAN14', 'Cyle Larin', 'Canadá', 'CAN', 'Canadá', 14, 'jugador', 'normal', 113),
(115, 'CAN15', 'Jacob Shaffelburg', 'Canadá', 'CAN', 'Canadá', 15, 'jugador', 'shiny', 114),
(116, 'CAN16', 'Ismaël Koné', 'Canadá', 'CAN', 'Canadá', 16, 'jugador', 'normal', 115),
(117, 'CAN17', 'Junior Hoilett', 'Canadá', 'CAN', 'Canadá', 17, 'jugador', 'shiny', 116),
(118, 'CAN18', 'Lucas Cavallini', 'Canadá', 'CAN', 'Canadá', 18, 'jugador', 'normal', 117),
(119, 'CAN19', 'Mark-Anthony Kaye', 'Canadá', 'CAN', 'Canadá', 19, 'jugador', 'normal', 118),
(120, 'CAN20', 'Kamal Miller', 'Canadá', 'CAN', 'Canadá', 20, 'jugador', 'normal', 119),
(121, 'SUI1', 'Escudo Suiza', 'Suiza', 'SUI', 'Suiza', 1, 'escudo', 'shiny', 120),
(122, 'SUI2', 'Yann Sommer', 'Suiza', 'SUI', 'Suiza', 2, 'jugador', 'normal', 121),
(123, 'SUI3', 'Manuel Akanji', 'Suiza', 'SUI', 'Suiza', 3, 'jugador', 'normal', 122),
(124, 'SUI4', 'Nico Elvedi', 'Suiza', 'SUI', 'Suiza', 4, 'jugador', 'normal', 123),
(125, 'SUI5', 'Ricardo Rodríguez', 'Suiza', 'SUI', 'Suiza', 5, 'jugador', 'normal', 124),
(126, 'SUI6', 'Silvan Widmer', 'Suiza', 'SUI', 'Suiza', 6, 'jugador', 'normal', 125),
(127, 'SUI7', 'Granit Xhaka', 'Suiza', 'SUI', 'Suiza', 7, 'jugador', 'normal', 126),
(128, 'SUI8', 'Remo Freuler', 'Suiza', 'SUI', 'Suiza', 8, 'jugador', 'normal', 127),
(129, 'SUI9', 'Ruben Vargas', 'Suiza', 'SUI', 'Suiza', 9, 'jugador', 'normal', 128),
(130, 'SUI10', 'Breel Embolo', 'Suiza', 'SUI', 'Suiza', 10, 'jugador', 'shiny', 129),
(131, 'SUI11', 'Xherdan Shaqiri', 'Suiza', 'SUI', 'Suiza', 11, 'jugador', 'normal', 130),
(132, 'SUI12', 'Dan Ndoye', 'Suiza', 'SUI', 'Suiza', 12, 'jugador', 'normal', 131),
(133, 'SUI13', 'Foto de equipo', 'Suiza', 'SUI', 'Suiza', 13, 'foto_equipo', 'special', 132),
(134, 'SUI14', 'Michel Rieder', 'Suiza', 'SUI', 'Suiza', 14, 'jugador', 'normal', 133),
(135, 'SUI15', 'Fabian Schär', 'Suiza', 'SUI', 'Suiza', 15, 'jugador', 'shiny', 134),
(136, 'SUI16', 'Denis Zakaria', 'Suiza', 'SUI', 'Suiza', 16, 'jugador', 'normal', 135),
(137, 'SUI17', 'Vincent Sierro', 'Suiza', 'SUI', 'Suiza', 17, 'jugador', 'shiny', 136),
(138, 'SUI18', 'Steven Zuber', 'Suiza', 'SUI', 'Suiza', 18, 'jugador', 'normal', 137),
(139, 'SUI19', 'Noah Okafor', 'Suiza', 'SUI', 'Suiza', 19, 'jugador', 'normal', 138),
(140, 'SUI20', 'Gregor Kobel', 'Suiza', 'SUI', 'Suiza', 20, 'jugador', 'normal', 139),
(141, 'QAT1', 'Escudo Qatar', 'Qatar', 'QAT', 'Qatar', 1, 'escudo', 'shiny', 140),
(142, 'QAT2', 'Saad Al-Sheeb', 'Qatar', 'QAT', 'Qatar', 2, 'jugador', 'normal', 141),
(143, 'QAT3', 'Akram Afif', 'Qatar', 'QAT', 'Qatar', 3, 'jugador', 'normal', 142),
(144, 'QAT4', 'Almoez Ali', 'Qatar', 'QAT', 'Qatar', 4, 'jugador', 'normal', 143),
(145, 'QAT5', 'Hassan Al-Haydos', 'Qatar', 'QAT', 'Qatar', 5, 'jugador', 'normal', 144),
(146, 'QAT6', 'Abdelkarim Hassan', 'Qatar', 'QAT', 'Qatar', 6, 'jugador', 'normal', 145),
(147, 'QAT7', 'Boualem Khoukhi', 'Qatar', 'QAT', 'Qatar', 7, 'jugador', 'normal', 146),
(148, 'QAT8', 'Karim Boudiaf', 'Qatar', 'QAT', 'Qatar', 8, 'jugador', 'normal', 147),
(149, 'QAT9', 'Yousuf Abdurisag', 'Qatar', 'QAT', 'Qatar', 9, 'jugador', 'normal', 148),
(150, 'QAT10', 'Homam Ahmed', 'Qatar', 'QAT', 'Qatar', 10, 'jugador', 'shiny', 149),
(151, 'QAT11', 'Musab Khoder', 'Qatar', 'QAT', 'Qatar', 11, 'jugador', 'normal', 150),
(152, 'QAT12', 'Tarek Salman', 'Qatar', 'QAT', 'Qatar', 12, 'jugador', 'normal', 151),
(153, 'QAT13', 'Foto de equipo', 'Qatar', 'QAT', 'Qatar', 13, 'foto_equipo', 'special', 152),
(154, 'QAT14', 'Pedro Miguel', 'Qatar', 'QAT', 'Qatar', 14, 'jugador', 'normal', 153),
(155, 'QAT15', 'Ahmed Fadl', 'Qatar', 'QAT', 'Qatar', 15, 'jugador', 'shiny', 154),
(156, 'QAT16', 'Mohammed Muntari', 'Qatar', 'QAT', 'Qatar', 16, 'jugador', 'normal', 155),
(157, 'QAT17', 'Ali Asad', 'Qatar', 'QAT', 'Qatar', 17, 'jugador', 'shiny', 156),
(158, 'QAT18', 'Bassam Al-Rawi', 'Qatar', 'QAT', 'Qatar', 18, 'jugador', 'normal', 157),
(159, 'QAT19', 'Abdulaziz Hatem', 'Qatar', 'QAT', 'Qatar', 19, 'jugador', 'normal', 158),
(160, 'QAT20', 'Meshaal Barsham', 'Qatar', 'QAT', 'Qatar', 20, 'jugador', 'normal', 159),
(161, 'BIH1', 'Escudo Bosnia y Herzegovina', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 1, 'escudo', 'shiny', 160),
(162, 'BIH2', 'Edin Džeko', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 2, 'jugador', 'normal', 161),
(163, 'BIH3', 'Miralem Pjanić', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 3, 'jugador', 'normal', 162),
(164, 'BIH4', 'Sead Kolašinac', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 4, 'jugador', 'normal', 163),
(165, 'BIH5', 'Ermedin Demirović', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 5, 'jugador', 'normal', 164),
(166, 'BIH6', 'Amir Hadžiahmetović', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 6, 'jugador', 'normal', 165),
(167, 'BIH7', 'Muhamed Bešić', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 7, 'jugador', 'normal', 166),
(168, 'BIH8', 'Anel Ahmedhodžić', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 8, 'jugador', 'normal', 167),
(169, 'BIH9', 'Elvis Sarić', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 9, 'jugador', 'normal', 168),
(170, 'BIH10', 'Benjamin Tahirović', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 10, 'jugador', 'shiny', 169),
(171, 'BIH11', 'Dino Perić', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 11, 'jugador', 'normal', 170),
(172, 'BIH12', 'Kenan Kodro', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 12, 'jugador', 'normal', 171),
(173, 'BIH13', 'Foto de equipo', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 13, 'foto_equipo', 'special', 172),
(174, 'BIH14', 'Ibrahim Šehić', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 14, 'jugador', 'normal', 173),
(175, 'BIH15', 'Miroslav Stevanović', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 15, 'jugador', 'shiny', 174),
(176, 'BIH16', 'Stjepan Lončar', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 16, 'jugador', 'normal', 175),
(177, 'BIH17', 'Adis Jahović', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 17, 'jugador', 'shiny', 176),
(178, 'BIH18', 'Tarik Muharemović', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 18, 'jugador', 'normal', 177),
(179, 'BIH19', 'Dennis Hadžikadunić', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 19, 'jugador', 'normal', 178),
(180, 'BIH20', 'Amer Gojak', 'Bosnia y Herzegovina', 'BIH', 'Bosnia y Herzegovina', 20, 'jugador', 'normal', 179),
(181, 'BRA1', 'Escudo Brasil', 'Brasil', 'BRA', 'Brasil', 1, 'escudo', 'shiny', 180),
(182, 'BRA2', 'Alisson', 'Brasil', 'BRA', 'Brasil', 2, 'jugador', 'normal', 181),
(183, 'BRA3', 'Danilo', 'Brasil', 'BRA', 'Brasil', 3, 'jugador', 'normal', 182),
(184, 'BRA4', 'Marquinhos', 'Brasil', 'BRA', 'Brasil', 4, 'jugador', 'normal', 183),
(185, 'BRA5', 'Gabriel Magalhães', 'Brasil', 'BRA', 'Brasil', 5, 'jugador', 'normal', 184),
(186, 'BRA6', 'Guimarães', 'Brasil', 'BRA', 'Brasil', 6, 'jugador', 'normal', 185),
(187, 'BRA7', 'Casemiro', 'Brasil', 'BRA', 'Brasil', 7, 'jugador', 'normal', 186),
(188, 'BRA8', 'Bruno Guimarães', 'Brasil', 'BRA', 'Brasil', 8, 'jugador', 'normal', 187),
(189, 'BRA9', 'Paquetá', 'Brasil', 'BRA', 'Brasil', 9, 'jugador', 'normal', 188),
(190, 'BRA10', 'Rodrygo', 'Brasil', 'BRA', 'Brasil', 10, 'jugador', 'shiny', 189),
(191, 'BRA11', 'Vinícius Jr', 'Brasil', 'BRA', 'Brasil', 11, 'jugador', 'normal', 190),
(192, 'BRA12', 'Raphinha', 'Brasil', 'BRA', 'Brasil', 12, 'jugador', 'normal', 191),
(193, 'BRA13', 'Foto de equipo', 'Brasil', 'BRA', 'Brasil', 13, 'foto_equipo', 'special', 192),
(194, 'BRA14', 'Neymar', 'Brasil', 'BRA', 'Brasil', 14, 'jugador', 'normal', 193),
(195, 'BRA15', 'Richarlison', 'Brasil', 'BRA', 'Brasil', 15, 'jugador', 'shiny', 194),
(196, 'BRA16', 'Endrick', 'Brasil', 'BRA', 'Brasil', 16, 'jugador', 'normal', 195),
(197, 'BRA17', 'Martinelli', 'Brasil', 'BRA', 'Brasil', 17, 'jugador', 'shiny', 196),
(198, 'BRA18', 'Bremer', 'Brasil', 'BRA', 'Brasil', 18, 'jugador', 'normal', 197),
(199, 'BRA19', 'Wesley', 'Brasil', 'BRA', 'Brasil', 19, 'jugador', 'normal', 198),
(200, 'BRA20', 'Bento', 'Brasil', 'BRA', 'Brasil', 20, 'jugador', 'normal', 199),
(201, 'MAR1', 'Escudo Marruecos', 'Marruecos', 'MAR', 'Marruecos', 1, 'escudo', 'shiny', 200),
(202, 'MAR2', 'Yassine Bounou', 'Marruecos', 'MAR', 'Marruecos', 2, 'jugador', 'normal', 201),
(203, 'MAR3', 'Achraf Hakimi', 'Marruecos', 'MAR', 'Marruecos', 3, 'jugador', 'normal', 202),
(204, 'MAR4', 'Romain Saiss', 'Marruecos', 'MAR', 'Marruecos', 4, 'jugador', 'normal', 203),
(205, 'MAR5', 'Nayef Aguerd', 'Marruecos', 'MAR', 'Marruecos', 5, 'jugador', 'normal', 204),
(206, 'MAR6', 'Noussair Mazraoui', 'Marruecos', 'MAR', 'Marruecos', 6, 'jugador', 'normal', 205),
(207, 'MAR7', 'Sofyan Amrabat', 'Marruecos', 'MAR', 'Marruecos', 7, 'jugador', 'normal', 206),
(208, 'MAR8', 'Azzedine Ounahi', 'Marruecos', 'MAR', 'Marruecos', 8, 'jugador', 'normal', 207),
(209, 'MAR9', 'Hakim Ziyech', 'Marruecos', 'MAR', 'Marruecos', 9, 'jugador', 'normal', 208),
(210, 'MAR10', 'Youssef En-Nesyri', 'Marruecos', 'MAR', 'Marruecos', 10, 'jugador', 'shiny', 209),
(211, 'MAR11', 'Sofiane Boufal', 'Marruecos', 'MAR', 'Marruecos', 11, 'jugador', 'normal', 210),
(212, 'MAR12', 'Selim Amallah', 'Marruecos', 'MAR', 'Marruecos', 12, 'jugador', 'normal', 211),
(213, 'MAR13', 'Foto de equipo', 'Marruecos', 'MAR', 'Marruecos', 13, 'foto_equipo', 'special', 212),
(214, 'MAR14', 'Brahim Díaz', 'Marruecos', 'MAR', 'Marruecos', 14, 'jugador', 'normal', 213),
(215, 'MAR15', 'Abde Ezzalzouli', 'Marruecos', 'MAR', 'Marruecos', 15, 'jugador', 'shiny', 214),
(216, 'MAR16', 'Ilias Akhomach', 'Marruecos', 'MAR', 'Marruecos', 16, 'jugador', 'normal', 215),
(217, 'MAR17', 'Walid Cheddira', 'Marruecos', 'MAR', 'Marruecos', 17, 'jugador', 'shiny', 216),
(218, 'MAR18', 'Yahya Attiat-Allah', 'Marruecos', 'MAR', 'Marruecos', 18, 'jugador', 'normal', 217),
(219, 'MAR19', 'Munir El Kadiri', 'Marruecos', 'MAR', 'Marruecos', 19, 'jugador', 'normal', 218),
(220, 'MAR20', 'Zakaria Aboukhlal', 'Marruecos', 'MAR', 'Marruecos', 20, 'jugador', 'normal', 219),
(221, 'SCO1', 'Escudo Escocia', 'Escocia', 'SCO', 'Escocia', 1, 'escudo', 'shiny', 220),
(222, 'SCO2', 'Angus Gunn', 'Escocia', 'SCO', 'Escocia', 2, 'jugador', 'normal', 221),
(223, 'SCO3', 'Kieran Tierney', 'Escocia', 'SCO', 'Escocia', 3, 'jugador', 'normal', 222),
(224, 'SCO4', 'Scott McTominay', 'Escocia', 'SCO', 'Escocia', 4, 'jugador', 'normal', 223),
(225, 'SCO5', 'John McGinn', 'Escocia', 'SCO', 'Escocia', 5, 'jugador', 'normal', 224),
(226, 'SCO6', 'Andy Robertson', 'Escocia', 'SCO', 'Escocia', 6, 'jugador', 'normal', 225),
(227, 'SCO7', 'Che Adams', 'Escocia', 'SCO', 'Escocia', 7, 'jugador', 'normal', 226),
(228, 'SCO8', 'Lyndon Dykes', 'Escocia', 'SCO', 'Escocia', 8, 'jugador', 'normal', 227),
(229, 'SCO9', 'Ryan Christie', 'Escocia', 'SCO', 'Escocia', 9, 'jugador', 'normal', 228),
(230, 'SCO10', 'Lewis Ferguson', 'Escocia', 'SCO', 'Escocia', 10, 'jugador', 'shiny', 229),
(231, 'SCO11', 'Billy Gilmour', 'Escocia', 'SCO', 'Escocia', 11, 'jugador', 'normal', 230),
(232, 'SCO12', 'Grant Hanley', 'Escocia', 'SCO', 'Escocia', 12, 'jugador', 'normal', 231),
(233, 'SCO13', 'Foto de equipo', 'Escocia', 'SCO', 'Escocia', 13, 'foto_equipo', 'special', 232),
(234, 'SCO14', 'Jack Hendry', 'Escocia', 'SCO', 'Escocia', 14, 'jugador', 'normal', 233),
(235, 'SCO15', 'Anthony Ralston', 'Escocia', 'SCO', 'Escocia', 15, 'jugador', 'shiny', 234),
(236, 'SCO16', 'Kenny McLean', 'Escocia', 'SCO', 'Escocia', 16, 'jugador', 'normal', 235),
(237, 'SCO17', 'Lawrence Shankland', 'Escocia', 'SCO', 'Escocia', 17, 'jugador', 'shiny', 236),
(238, 'SCO18', 'Ross McCrorie', 'Escocia', 'SCO', 'Escocia', 18, 'jugador', 'normal', 237),
(239, 'SCO19', 'Greg Taylor', 'Escocia', 'SCO', 'Escocia', 19, 'jugador', 'normal', 238),
(240, 'SCO20', 'Liam Palmer', 'Escocia', 'SCO', 'Escocia', 20, 'jugador', 'normal', 239),
(241, 'HAI1', 'Escudo Haití', 'Haití', 'HAI', 'Haití', 1, 'escudo', 'shiny', 240),
(242, 'HAI2', 'Duckens Nazon', 'Haití', 'HAI', 'Haití', 2, 'jugador', 'normal', 241),
(243, 'HAI3', 'Zachary Herivaux', 'Haití', 'HAI', 'Haití', 3, 'jugador', 'normal', 242),
(244, 'HAI4', 'Derrick Etienne', 'Haití', 'HAI', 'Haití', 4, 'jugador', 'normal', 243),
(245, 'HAI5', 'Johny Placide', 'Haití', 'HAI', 'Haití', 5, 'jugador', 'normal', 244),
(246, 'HAI6', 'Carlens Arcus', 'Haití', 'HAI', 'Haití', 6, 'jugador', 'normal', 245),
(247, 'HAI7', 'Steeven Saba', 'Haití', 'HAI', 'Haití', 7, 'jugador', 'normal', 246),
(248, 'HAI8', 'Bryan Alceus', 'Haití', 'HAI', 'Haití', 8, 'jugador', 'normal', 247),
(249, 'HAI9', 'Mickael Miro', 'Haití', 'HAI', 'Haití', 9, 'jugador', 'normal', 248),
(250, 'HAI10', 'Danley Jean Jacques', 'Haití', 'HAI', 'Haití', 10, 'jugador', 'shiny', 249),
(251, 'HAI11', 'Frantzdy Pierrot', 'Haití', 'HAI', 'Haití', 11, 'jugador', 'normal', 250),
(252, 'HAI12', 'Carnejy Antoine', 'Haití', 'HAI', 'Haití', 12, 'jugador', 'normal', 251),
(253, 'HAI13', 'Foto de equipo', 'Haití', 'HAI', 'Haití', 13, 'foto_equipo', 'special', 252),
(254, 'HAI14', 'Alexandre Pierre', 'Haití', 'HAI', 'Haití', 14, 'jugador', 'normal', 253),
(255, 'HAI15', 'Ricardo Adé', 'Haití', 'HAI', 'Haití', 15, 'jugador', 'shiny', 254),
(256, 'HAI16', 'Martinique', 'Haití', 'HAI', 'Haití', 16, 'jugador', 'normal', 255),
(257, 'HAI17', 'Woodensky Bernard', 'Haití', 'HAI', 'Haití', 17, 'jugador', 'shiny', 256),
(258, 'HAI18', 'Dany Jean', 'Haití', 'HAI', 'Haití', 18, 'jugador', 'normal', 257),
(259, 'HAI19', 'Jems Geffrard', 'Haití', 'HAI', 'Haití', 19, 'jugador', 'normal', 258),
(260, 'HAI20', 'Bélinson Poly', 'Haití', 'HAI', 'Haití', 20, 'jugador', 'normal', 259),
(261, 'USA1', 'Escudo Estados Unidos', 'Estados Unidos', 'USA', 'Estados Unidos', 1, 'escudo', 'shiny', 260),
(262, 'USA2', 'Matt Turner', 'Estados Unidos', 'USA', 'Estados Unidos', 2, 'jugador', 'normal', 261),
(263, 'USA3', 'Sergiño Dest', 'Estados Unidos', 'USA', 'Estados Unidos', 3, 'jugador', 'normal', 262),
(264, 'USA4', 'Chris Richards', 'Estados Unidos', 'USA', 'Estados Unidos', 4, 'jugador', 'normal', 263),
(265, 'USA5', 'Antonee Robinson', 'Estados Unidos', 'USA', 'Estados Unidos', 5, 'jugador', 'normal', 264),
(266, 'USA6', 'Walker Zimmerman', 'Estados Unidos', 'USA', 'Estados Unidos', 6, 'jugador', 'normal', 265),
(267, 'USA7', 'Tyler Adams', 'Estados Unidos', 'USA', 'Estados Unidos', 7, 'jugador', 'normal', 266),
(268, 'USA8', 'Yunus Musah', 'Estados Unidos', 'USA', 'Estados Unidos', 8, 'jugador', 'normal', 267),
(269, 'USA9', 'Weston McKennie', 'Estados Unidos', 'USA', 'Estados Unidos', 9, 'jugador', 'normal', 268),
(270, 'USA10', 'Gio Reyna', 'Estados Unidos', 'USA', 'Estados Unidos', 10, 'jugador', 'shiny', 269),
(271, 'USA11', 'Christian Pulisic', 'Estados Unidos', 'USA', 'Estados Unidos', 11, 'jugador', 'normal', 270),
(272, 'USA12', 'Ricardo Pepi', 'Estados Unidos', 'USA', 'Estados Unidos', 12, 'jugador', 'normal', 271),
(273, 'USA13', 'Foto de equipo', 'Estados Unidos', 'USA', 'Estados Unidos', 13, 'foto_equipo', 'special', 272),
(274, 'USA14', 'Folarin Balogun', 'Estados Unidos', 'USA', 'Estados Unidos', 14, 'jugador', 'normal', 273),
(275, 'USA15', 'Haji Wright', 'Estados Unidos', 'USA', 'Estados Unidos', 15, 'jugador', 'shiny', 274),
(276, 'USA16', 'Josh Sargent', 'Estados Unidos', 'USA', 'Estados Unidos', 16, 'jugador', 'normal', 275),
(277, 'USA17', 'Brenden Aaronson', 'Estados Unidos', 'USA', 'Estados Unidos', 17, 'jugador', 'shiny', 276),
(278, 'USA18', 'Tim Weah', 'Estados Unidos', 'USA', 'Estados Unidos', 18, 'jugador', 'normal', 277),
(279, 'USA19', 'Johnny Cardoso', 'Estados Unidos', 'USA', 'Estados Unidos', 19, 'jugador', 'normal', 278),
(280, 'USA20', 'Malik Tillman', 'Estados Unidos', 'USA', 'Estados Unidos', 20, 'jugador', 'normal', 279),
(281, 'PAR1', 'Escudo Paraguay', 'Paraguay', 'PAR', 'Paraguay', 1, 'escudo', 'shiny', 280),
(282, 'PAR2', 'Carlos Coronel', 'Paraguay', 'PAR', 'Paraguay', 2, 'jugador', 'normal', 281),
(283, 'PAR3', 'Gustavo Gómez', 'Paraguay', 'PAR', 'Paraguay', 3, 'jugador', 'normal', 282),
(284, 'PAR4', 'Júnior Alonso', 'Paraguay', 'PAR', 'Paraguay', 4, 'jugador', 'normal', 283),
(285, 'PAR5', 'Omar Alderete', 'Paraguay', 'PAR', 'Paraguay', 5, 'jugador', 'normal', 284),
(286, 'PAR6', 'Matías Rojas', 'Paraguay', 'PAR', 'Paraguay', 6, 'jugador', 'normal', 285),
(287, 'PAR7', 'Richard Sánchez', 'Paraguay', 'PAR', 'Paraguay', 7, 'jugador', 'normal', 286),
(288, 'PAR8', 'Miguel Almirón', 'Paraguay', 'PAR', 'Paraguay', 8, 'jugador', 'normal', 287),
(289, 'PAR9', 'Julio Enciso', 'Paraguay', 'PAR', 'Paraguay', 9, 'jugador', 'normal', 288),
(290, 'PAR10', 'Ramón Sosa', 'Paraguay', 'PAR', 'Paraguay', 10, 'jugador', 'shiny', 289),
(291, 'PAR11', 'Antonio Sanabria', 'Paraguay', 'PAR', 'Paraguay', 11, 'jugador', 'normal', 290),
(292, 'PAR12', 'Alejandro Romero', 'Paraguay', 'PAR', 'Paraguay', 12, 'jugador', 'normal', 291),
(293, 'PAR13', 'Foto de equipo', 'Paraguay', 'PAR', 'Paraguay', 13, 'foto_equipo', 'special', 292),
(294, 'PAR14', 'Adam Bareiro', 'Paraguay', 'PAR', 'Paraguay', 14, 'jugador', 'normal', 293),
(295, 'PAR15', 'Diego Gómez', 'Paraguay', 'PAR', 'Paraguay', 15, 'jugador', 'shiny', 294),
(296, 'PAR16', 'Matías Galarza', 'Paraguay', 'PAR', 'Paraguay', 16, 'jugador', 'normal', 295),
(297, 'PAR17', 'Iván Ramírez', 'Paraguay', 'PAR', 'Paraguay', 17, 'jugador', 'shiny', 296),
(298, 'PAR18', 'Blas Riveros', 'Paraguay', 'PAR', 'Paraguay', 18, 'jugador', 'normal', 297),
(299, 'PAR19', 'Juan Iturbe', 'Paraguay', 'PAR', 'Paraguay', 19, 'jugador', 'normal', 298),
(300, 'PAR20', 'Héctor Caballero', 'Paraguay', 'PAR', 'Paraguay', 20, 'jugador', 'normal', 299),
(301, 'AUS1', 'Escudo Australia', 'Australia', 'AUS', 'Australia', 1, 'escudo', 'shiny', 300),
(302, 'AUS2', 'Mathew Ryan', 'Australia', 'AUS', 'Australia', 2, 'jugador', 'normal', 301),
(303, 'AUS3', 'Harry Souttar', 'Australia', 'AUS', 'Australia', 3, 'jugador', 'normal', 302),
(304, 'AUS4', 'Kye Rowles', 'Australia', 'AUS', 'Australia', 4, 'jugador', 'normal', 303),
(305, 'AUS5', 'Aziz Behich', 'Australia', 'AUS', 'Australia', 5, 'jugador', 'normal', 304),
(306, 'AUS6', 'Jackson Irvine', 'Australia', 'AUS', 'Australia', 6, 'jugador', 'normal', 305),
(307, 'AUS7', 'Riley McGree', 'Australia', 'AUS', 'Australia', 7, 'jugador', 'normal', 306),
(308, 'AUS8', 'Craig Goodwin', 'Australia', 'AUS', 'Australia', 8, 'jugador', 'normal', 307),
(309, 'AUS9', 'Mitchell Duke', 'Australia', 'AUS', 'Australia', 9, 'jugador', 'normal', 308),
(310, 'AUS10', 'Martin Boyle', 'Australia', 'AUS', 'Australia', 10, 'jugador', 'shiny', 309),
(311, 'AUS11', 'Awer Mabil', 'Australia', 'AUS', 'Australia', 11, 'jugador', 'normal', 310),
(312, 'AUS12', 'Adam Taggart', 'Australia', 'AUS', 'Australia', 12, 'jugador', 'normal', 311),
(313, 'AUS13', 'Foto de equipo', 'Australia', 'AUS', 'Australia', 13, 'foto_equipo', 'special', 312),
(314, 'AUS14', 'Mathew Leckie', 'Australia', 'AUS', 'Australia', 14, 'jugador', 'normal', 313),
(315, 'AUS15', 'Bailey Wright', 'Australia', 'AUS', 'Australia', 15, 'jugador', 'shiny', 314),
(316, 'AUS16', 'Keanu Baccus', 'Australia', 'AUS', 'Australia', 16, 'jugador', 'normal', 315),
(317, 'AUS17', 'Connor Metcalfe', 'Australia', 'AUS', 'Australia', 17, 'jugador', 'shiny', 316),
(318, 'AUS18', 'Graham Arnold', 'Australia', 'AUS', 'Australia', 18, 'jugador', 'normal', 317),
(319, 'AUS19', 'Nathaniel Atkinson', 'Australia', 'AUS', 'Australia', 19, 'jugador', 'normal', 318),
(320, 'AUS20', 'Deniz Gul', 'Australia', 'AUS', 'Australia', 20, 'jugador', 'normal', 319),
(321, 'TUR1', 'Escudo Turquía', 'Turquía', 'TUR', 'Turquía', 1, 'escudo', 'shiny', 320),
(322, 'TUR2', 'Uğurcan Çakır', 'Turquía', 'TUR', 'Turquía', 2, 'jugador', 'normal', 321),
(323, 'TUR3', 'Merih Demiral', 'Turquía', 'TUR', 'Turquía', 3, 'jugador', 'normal', 322),
(324, 'TUR4', 'Çağlar Söyüncü', 'Turquía', 'TUR', 'Turquía', 4, 'jugador', 'normal', 323),
(325, 'TUR5', 'Zeki Çelik', 'Turquía', 'TUR', 'Turquía', 5, 'jugador', 'normal', 324),
(326, 'TUR6', 'Hakan Çalhanoğlu', 'Turquía', 'TUR', 'Turquía', 6, 'jugador', 'normal', 325),
(327, 'TUR7', 'Arda Güler', 'Turquía', 'TUR', 'Turquía', 7, 'jugador', 'normal', 326),
(328, 'TUR8', 'Kenan Yıldız', 'Turquía', 'TUR', 'Turquía', 8, 'jugador', 'normal', 327),
(329, 'TUR9', 'Barış Alper Yılmaz', 'Turquía', 'TUR', 'Turquía', 9, 'jugador', 'normal', 328),
(330, 'TUR10', 'Cengiz Ünder', 'Turquía', 'TUR', 'Turquía', 10, 'jugador', 'shiny', 329),
(331, 'TUR11', 'Burak Yılmaz', 'Turquía', 'TUR', 'Turquía', 11, 'jugador', 'normal', 330),
(332, 'TUR12', 'Orkun Kökçü', 'Turquía', 'TUR', 'Turquía', 12, 'jugador', 'normal', 331),
(333, 'TUR13', 'Foto de equipo', 'Turquía', 'TUR', 'Turquía', 13, 'foto_equipo', 'special', 332),
(334, 'TUR14', 'İrfan Can Kahveci', 'Turquía', 'TUR', 'Turquía', 14, 'jugador', 'normal', 333),
(335, 'TUR15', 'Yunus Akgün', 'Turquía', 'TUR', 'Turquía', 15, 'jugador', 'shiny', 334),
(336, 'TUR16', 'Salih Özcan', 'Turquía', 'TUR', 'Turquía', 16, 'jugador', 'normal', 335),
(337, 'TUR17', 'Ferdi Kadıoğlu', 'Turquía', 'TUR', 'Turquía', 17, 'jugador', 'shiny', 336),
(338, 'TUR18', 'Abdülkerim Bardakcı', 'Turquía', 'TUR', 'Turquía', 18, 'jugador', 'normal', 337),
(339, 'TUR19', 'Mert Müldür', 'Turquía', 'TUR', 'Turquía', 19, 'jugador', 'normal', 338),
(340, 'TUR20', 'Vedat Bora', 'Turquía', 'TUR', 'Turquía', 20, 'jugador', 'normal', 339),
(341, 'GER1', 'Escudo Alemania', 'Alemania', 'GER', 'Alemania', 1, 'escudo', 'shiny', 340),
(342, 'GER2', 'Manuel Neuer', 'Alemania', 'GER', 'Alemania', 2, 'jugador', 'normal', 341),
(343, 'GER3', 'Joshua Kimmich', 'Alemania', 'GER', 'Alemania', 3, 'jugador', 'normal', 342),
(344, 'GER4', 'Antonio Rüdiger', 'Alemania', 'GER', 'Alemania', 4, 'jugador', 'normal', 343),
(345, 'GER5', 'Jonathan Tah', 'Alemania', 'GER', 'Alemania', 5, 'jugador', 'normal', 344),
(346, 'GER6', 'David Raum', 'Alemania', 'GER', 'Alemania', 6, 'jugador', 'normal', 345),
(347, 'GER7', 'Ilkay Gündogan', 'Alemania', 'GER', 'Alemania', 7, 'jugador', 'normal', 346),
(348, 'GER8', 'Jamal Musiala', 'Alemania', 'GER', 'Alemania', 8, 'jugador', 'normal', 347),
(349, 'GER9', 'Florian Wirtz', 'Alemania', 'GER', 'Alemania', 9, 'jugador', 'normal', 348),
(350, 'GER10', 'Leroy Sané', 'Alemania', 'GER', 'Alemania', 10, 'jugador', 'shiny', 349),
(351, 'GER11', 'Kai Havertz', 'Alemania', 'GER', 'Alemania', 11, 'jugador', 'normal', 350),
(352, 'GER12', 'Niclas Füllkrug', 'Alemania', 'GER', 'Alemania', 12, 'jugador', 'normal', 351),
(353, 'GER13', 'Foto de equipo', 'Alemania', 'GER', 'Alemania', 13, 'foto_equipo', 'special', 352),
(354, 'GER14', 'Thomas Müller', 'Alemania', 'GER', 'Alemania', 14, 'jugador', 'normal', 353),
(355, 'GER15', 'Serge Gnabry', 'Alemania', 'GER', 'Alemania', 15, 'jugador', 'shiny', 354),
(356, 'GER16', 'Jonas Hofmann', 'Alemania', 'GER', 'Alemania', 16, 'jugador', 'normal', 355),
(357, 'GER17', 'Felix Nmecha', 'Alemania', 'GER', 'Alemania', 17, 'jugador', 'shiny', 356),
(358, 'GER18', 'Benjamin Henrichs', 'Alemania', 'GER', 'Alemania', 18, 'jugador', 'normal', 357),
(359, 'GER19', 'Robin Gosens', 'Alemania', 'GER', 'Alemania', 19, 'jugador', 'normal', 358),
(360, 'GER20', 'Oliver Baumann', 'Alemania', 'GER', 'Alemania', 20, 'jugador', 'normal', 359),
(361, 'ECU1', 'Escudo Ecuador', 'Ecuador', 'ECU', 'Ecuador', 1, 'escudo', 'shiny', 360),
(362, 'ECU2', 'Alexander Domínguez', 'Ecuador', 'ECU', 'Ecuador', 2, 'jugador', 'normal', 361),
(363, 'ECU3', 'Pervis Estupiñán', 'Ecuador', 'ECU', 'Ecuador', 3, 'jugador', 'normal', 362),
(364, 'ECU4', 'Piero Hincapié', 'Ecuador', 'ECU', 'Ecuador', 4, 'jugador', 'normal', 363),
(365, 'ECU5', 'Felix Torres', 'Ecuador', 'ECU', 'Ecuador', 5, 'jugador', 'normal', 364),
(366, 'ECU6', 'Angelo Preciado', 'Ecuador', 'ECU', 'Ecuador', 6, 'jugador', 'normal', 365),
(367, 'ECU7', 'Moisés Caicedo', 'Ecuador', 'ECU', 'Ecuador', 7, 'jugador', 'normal', 366),
(368, 'ECU8', 'Carlos Gruezo', 'Ecuador', 'ECU', 'Ecuador', 8, 'jugador', 'normal', 367),
(369, 'ECU9', 'Kendry Páez', 'Ecuador', 'ECU', 'Ecuador', 9, 'jugador', 'normal', 368),
(370, 'ECU10', 'Enner Valencia', 'Ecuador', 'ECU', 'Ecuador', 10, 'jugador', 'shiny', 369),
(371, 'ECU11', 'Jeremy Sarmiento', 'Ecuador', 'ECU', 'Ecuador', 11, 'jugador', 'normal', 370),
(372, 'ECU12', 'Willian Pacho', 'Ecuador', 'ECU', 'Ecuador', 12, 'jugador', 'normal', 371),
(373, 'ECU13', 'Foto de equipo', 'Ecuador', 'ECU', 'Ecuador', 13, 'foto_equipo', 'special', 372),
(374, 'ECU14', 'Moises Caicedo', 'Ecuador', 'ECU', 'Ecuador', 14, 'jugador', 'normal', 373),
(375, 'ECU15', 'Jhon Jairo Durán', 'Ecuador', 'ECU', 'Ecuador', 15, 'jugador', 'shiny', 374),
(376, 'ECU16', 'Jordy Caicedo', 'Ecuador', 'ECU', 'Ecuador', 16, 'jugador', 'normal', 375),
(377, 'ECU17', 'Alan Franco', 'Ecuador', 'ECU', 'Ecuador', 17, 'jugador', 'shiny', 376),
(378, 'ECU18', 'Janner Corozo', 'Ecuador', 'ECU', 'Ecuador', 18, 'jugador', 'normal', 377),
(379, 'ECU19', 'Kevin Rodriguez', 'Ecuador', 'ECU', 'Ecuador', 19, 'jugador', 'normal', 378),
(380, 'ECU20', 'Jordy Alcivar', 'Ecuador', 'ECU', 'Ecuador', 20, 'jugador', 'normal', 379),
(381, 'CIV1', 'Escudo Costa de Marfil', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 1, 'escudo', 'shiny', 380),
(382, 'CIV2', 'Nicolas Pépé', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 2, 'jugador', 'normal', 381),
(383, 'CIV3', 'Franck Kessié', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 3, 'jugador', 'normal', 382),
(384, 'CIV4', 'Sébastien Haller', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 4, 'jugador', 'normal', 383),
(385, 'CIV5', 'Wilfried Zaha', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 5, 'jugador', 'normal', 384),
(386, 'CIV6', 'Simon Adingra', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 6, 'jugador', 'normal', 385),
(387, 'CIV7', 'Ibrahim Sangaré', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 7, 'jugador', 'normal', 386),
(388, 'CIV8', 'Odilon Kossounou', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 8, 'jugador', 'normal', 387),
(389, 'CIV9', 'Serge Aurier', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 9, 'jugador', 'normal', 388),
(390, 'CIV10', 'Yahia Fofana', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 10, 'jugador', 'shiny', 389),
(391, 'CIV11', 'Jean-Philippe Krasso', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 11, 'jugador', 'normal', 390),
(392, 'CIV12', 'Max-Alain Gradel', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 12, 'jugador', 'normal', 391),
(393, 'CIV13', 'Foto de equipo', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 13, 'foto_equipo', 'special', 392),
(394, 'CIV14', 'Jean Seri', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 14, 'jugador', 'normal', 393),
(395, 'CIV15', 'Habib Maïga', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 15, 'jugador', 'shiny', 394),
(396, 'CIV16', 'Ghislain Konan', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 16, 'jugador', 'normal', 395),
(397, 'CIV17', 'Karim Konaté', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 17, 'jugador', 'shiny', 396),
(398, 'CIV18', 'Amad Diallo', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 18, 'jugador', 'normal', 397),
(399, 'CIV19', 'Badra Ali Sangaré', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 19, 'jugador', 'normal', 398),
(400, 'CIV20', 'Ousmane Diomande', 'Costa de Marfil', 'CIV', 'Costa de Marfil', 20, 'jugador', 'normal', 399),
(401, 'CUW1', 'Escudo Curaçao', 'Curaçao', 'CUW', 'Curaçao', 1, 'escudo', 'shiny', 400),
(402, 'CUW2', 'Eloy Room', 'Curaçao', 'CUW', 'Curaçao', 2, 'jugador', 'normal', 401),
(403, 'CUW3', 'Cuco Martina', 'Curaçao', 'CUW', 'Curaçao', 3, 'jugador', 'normal', 402),
(404, 'CUW4', 'Ridgeciano Hato', 'Curaçao', 'CUW', 'Curaçao', 4, 'jugador', 'normal', 403),
(405, 'CUW5', 'Juriën Gaari', 'Curaçao', 'CUW', 'Curaçao', 5, 'jugador', 'normal', 404),
(406, 'CUW6', 'Leandro Bacuna', 'Curaçao', 'CUW', 'Curaçao', 6, 'jugador', 'normal', 405),
(407, 'CUW7', 'Brandley Kuwas', 'Curaçao', 'CUW', 'Curaçao', 7, 'jugador', 'normal', 406),
(408, 'CUW8', 'Elson Hooi', 'Curaçao', 'CUW', 'Curaçao', 8, 'jugador', 'normal', 407),
(409, 'CUW9', 'Rangelo Janga', 'Curaçao', 'CUW', 'Curaçao', 9, 'jugador', 'normal', 408),
(410, 'CUW10', 'Shanon Carmelia', 'Curaçao', 'CUW', 'Curaçao', 10, 'jugador', 'shiny', 409),
(411, 'CUW11', 'Jarchinio Antonia', 'Curaçao', 'CUW', 'Curaçao', 11, 'jugador', 'normal', 410),
(412, 'CUW12', 'Gillian Japa', 'Curaçao', 'CUW', 'Curaçao', 12, 'jugador', 'normal', 411),
(413, 'CUW13', 'Foto de equipo', 'Curaçao', 'CUW', 'Curaçao', 13, 'foto_equipo', 'special', 412),
(414, 'CUW14', 'Ayrton Statie', 'Curaçao', 'CUW', 'Curaçao', 14, 'jugador', 'normal', 413),
(415, 'CUW15', 'Jurich Carolina', 'Curaçao', 'CUW', 'Curaçao', 15, 'jugador', 'shiny', 414),
(416, 'CUW16', 'Roshon van Eijma', 'Curaçao', 'CUW', 'Curaçao', 16, 'jugador', 'normal', 415),
(417, 'CUW17', 'Trevor Doornbos', 'Curaçao', 'CUW', 'Curaçao', 17, 'jugador', 'shiny', 416),
(418, 'CUW18', 'Juriën Gaari', 'Curaçao', 'CUW', 'Curaçao', 18, 'jugador', 'normal', 417),
(419, 'CUW19', 'Tyrique Mercera', 'Curaçao', 'CUW', 'Curaçao', 19, 'jugador', 'normal', 418),
(420, 'CUW20', 'Nigel Rosa', 'Curaçao', 'CUW', 'Curaçao', 20, 'jugador', 'normal', 419),
(421, 'NED1', 'Escudo Países Bajos', 'Países Bajos', 'NED', 'Países Bajos', 1, 'escudo', 'shiny', 420),
(422, 'NED2', 'Virgil van Dijk', 'Países Bajos', 'NED', 'Países Bajos', 2, 'jugador', 'normal', 421),
(423, 'NED3', 'Matthijs de Ligt', 'Países Bajos', 'NED', 'Países Bajos', 3, 'jugador', 'normal', 422),
(424, 'NED4', 'Nathan Aké', 'Países Bajos', 'NED', 'Países Bajos', 4, 'jugador', 'normal', 423),
(425, 'NED5', 'Denzel Dumfries', 'Países Bajos', 'NED', 'Países Bajos', 5, 'jugador', 'normal', 424),
(426, 'NED6', 'Steven Bergwijn', 'Países Bajos', 'NED', 'Países Bajos', 6, 'jugador', 'normal', 425),
(427, 'NED7', 'Frenkie de Jong', 'Países Bajos', 'NED', 'Países Bajos', 7, 'jugador', 'normal', 426),
(428, 'NED8', 'Georginio Wijnaldum', 'Países Bajos', 'NED', 'Países Bajos', 8, 'jugador', 'normal', 427),
(429, 'NED9', 'Cody Gakpo', 'Países Bajos', 'NED', 'Países Bajos', 9, 'jugador', 'normal', 428),
(430, 'NED10', 'Memphis Depay', 'Países Bajos', 'NED', 'Países Bajos', 10, 'jugador', 'shiny', 429),
(431, 'NED11', 'Steven Bergwijn', 'Países Bajos', 'NED', 'Países Bajos', 11, 'jugador', 'normal', 430),
(432, 'NED12', 'Donyell Malen', 'Países Bajos', 'NED', 'Países Bajos', 12, 'jugador', 'normal', 431),
(433, 'NED13', 'Foto de equipo', 'Países Bajos', 'NED', 'Países Bajos', 13, 'foto_equipo', 'special', 432),
(434, 'NED14', 'Brian Brobbey', 'Países Bajos', 'NED', 'Países Bajos', 14, 'jugador', 'normal', 433),
(435, 'NED15', 'Jeremie Frimpong', 'Países Bajos', 'NED', 'Países Bajos', 15, 'jugador', 'shiny', 434),
(436, 'NED16', 'Xavi Simons', 'Países Bajos', 'NED', 'Países Bajos', 16, 'jugador', 'normal', 435),
(437, 'NED17', 'Tijjani Reijnders', 'Países Bajos', 'NED', 'Países Bajos', 17, 'jugador', 'shiny', 436),
(438, 'NED18', 'Ian Maatsen', 'Países Bajos', 'NED', 'Países Bajos', 18, 'jugador', 'normal', 437),
(439, 'NED19', 'Micky van de Ven', 'Países Bajos', 'NED', 'Países Bajos', 19, 'jugador', 'normal', 438),
(440, 'NED20', 'Justin Bijlow', 'Países Bajos', 'NED', 'Países Bajos', 20, 'jugador', 'normal', 439),
(441, 'JPN1', 'Escudo Japón', 'Japón', 'JPN', 'Japón', 1, 'escudo', 'shiny', 440),
(442, 'JPN2', 'Takefusa Kubo', 'Japón', 'JPN', 'Japón', 2, 'jugador', 'normal', 441),
(443, 'JPN3', 'Kaoru Mitoma', 'Japón', 'JPN', 'Japón', 3, 'jugador', 'normal', 442),
(444, 'JPN4', 'Wataru Endo', 'Japón', 'JPN', 'Japón', 4, 'jugador', 'normal', 443),
(445, 'JPN5', 'Hiroki Ito', 'Japón', 'JPN', 'Japón', 5, 'jugador', 'normal', 444),
(446, 'JPN6', 'Ritsu Doan', 'Japón', 'JPN', 'Japón', 6, 'jugador', 'normal', 445),
(447, 'JPN7', 'Daizen Maeda', 'Japón', 'JPN', 'Japón', 7, 'jugador', 'normal', 446),
(448, 'JPN8', 'Ayase Ueda', 'Japón', 'JPN', 'Japón', 8, 'jugador', 'normal', 447),
(449, 'JPN9', 'Yuki Soma', 'Japón', 'JPN', 'Japón', 9, 'jugador', 'normal', 448),
(450, 'JPN10', 'Ko Itakura', 'Japón', 'JPN', 'Japón', 10, 'jugador', 'shiny', 449),
(451, 'JPN11', 'Reo Hatate', 'Japón', 'JPN', 'Japón', 11, 'jugador', 'normal', 450),
(452, 'JPN12', 'Junya Ito', 'Japón', 'JPN', 'Japón', 12, 'jugador', 'normal', 451),
(453, 'JPN13', 'Foto de equipo', 'Japón', 'JPN', 'Japón', 13, 'foto_equipo', 'special', 452),
(454, 'JPN14', 'Shuichi Gonda', 'Japón', 'JPN', 'Japón', 14, 'jugador', 'normal', 453),
(455, 'JPN15', 'Yuto Nagatomo', 'Japón', 'JPN', 'Japón', 15, 'jugador', 'shiny', 454),
(456, 'JPN16', 'Hidemasa Morita', 'Japón', 'JPN', 'Japón', 16, 'jugador', 'normal', 455),
(457, 'JPN17', 'Takumi Minamino', 'Japón', 'JPN', 'Japón', 17, 'jugador', 'shiny', 456),
(458, 'JPN18', 'Keito Nakamura', 'Japón', 'JPN', 'Japón', 18, 'jugador', 'normal', 457),
(459, 'JPN19', 'Shogo Taniguchi', 'Japón', 'JPN', 'Japón', 19, 'jugador', 'normal', 458),
(460, 'JPN20', 'Santiago Furukawa', 'Japón', 'JPN', 'Japón', 20, 'jugador', 'normal', 459),
(461, 'TUN1', 'Escudo Túnez', 'Túnez', 'TUN', 'Túnez', 1, 'escudo', 'shiny', 460),
(462, 'TUN2', 'Aïssa Laidouni', 'Túnez', 'TUN', 'Túnez', 2, 'jugador', 'normal', 461),
(463, 'TUN3', 'Wahbi Khazri', 'Túnez', 'TUN', 'Túnez', 3, 'jugador', 'normal', 462),
(464, 'TUN4', 'Youssef Msakni', 'Túnez', 'TUN', 'Túnez', 4, 'jugador', 'normal', 463),
(465, 'TUN5', 'Ellyes Skhiri', 'Túnez', 'TUN', 'Túnez', 5, 'jugador', 'normal', 464),
(466, 'TUN6', 'Nader Ghandri', 'Túnez', 'TUN', 'Túnez', 6, 'jugador', 'normal', 465),
(467, 'TUN7', 'Hamza Mathlouthi', 'Túnez', 'TUN', 'Túnez', 7, 'jugador', 'normal', 466),
(468, 'TUN8', 'Montassar Talbi', 'Túnez', 'TUN', 'Túnez', 8, 'jugador', 'normal', 467),
(469, 'TUN9', 'Ali Maaloul', 'Túnez', 'TUN', 'Túnez', 9, 'jugador', 'normal', 468),
(470, 'TUN10', 'Seifeddine Jaziri', 'Túnez', 'TUN', 'Túnez', 10, 'jugador', 'shiny', 469),
(471, 'TUN11', 'Taha Yassine Khenissi', 'Túnez', 'TUN', 'Túnez', 11, 'jugador', 'normal', 470),
(472, 'TUN12', 'Mohamed Dräger', 'Túnez', 'TUN', 'Túnez', 12, 'jugador', 'normal', 471),
(473, 'TUN13', 'Foto de equipo', 'Túnez', 'TUN', 'Túnez', 13, 'foto_equipo', 'special', 472),
(474, 'TUN14', 'Aymen Dahmen', 'Túnez', 'TUN', 'Túnez', 14, 'jugador', 'normal', 473),
(475, 'TUN15', 'Anis Ben Slimane', 'Túnez', 'TUN', 'Túnez', 15, 'jugador', 'shiny', 474),
(476, 'TUN16', 'Hamza Rafia', 'Túnez', 'TUN', 'Túnez', 16, 'jugador', 'normal', 475),
(477, 'TUN17', 'Ghailene Chaalali', 'Túnez', 'TUN', 'Túnez', 17, 'jugador', 'shiny', 476),
(478, 'TUN18', 'Oussama Khazri', 'Túnez', 'TUN', 'Túnez', 18, 'jugador', 'normal', 477),
(479, 'TUN19', 'Bilel Ifa', 'Túnez', 'TUN', 'Túnez', 19, 'jugador', 'normal', 478),
(480, 'TUN20', 'Yassine Meriah', 'Túnez', 'TUN', 'Túnez', 20, 'jugador', 'normal', 479),
(481, 'SWE1', 'Escudo Suecia', 'Suecia', 'SWE', 'Suecia', 1, 'escudo', 'shiny', 480),
(482, 'SWE2', 'Victor Lindelöf', 'Suecia', 'SWE', 'Suecia', 2, 'jugador', 'normal', 481),
(483, 'SWE3', 'Alexander Isak', 'Suecia', 'SWE', 'Suecia', 3, 'jugador', 'normal', 482),
(484, 'SWE4', 'Dejan Kulusevski', 'Suecia', 'SWE', 'Suecia', 4, 'jugador', 'normal', 483),
(485, 'SWE5', 'Emil Forsberg', 'Suecia', 'SWE', 'Suecia', 5, 'jugador', 'normal', 484),
(486, 'SWE6', 'Mattias Svanberg', 'Suecia', 'SWE', 'Suecia', 6, 'jugador', 'normal', 485),
(487, 'SWE7', 'Jesper Karlsson', 'Suecia', 'SWE', 'Suecia', 7, 'jugador', 'normal', 486),
(488, 'SWE8', 'Viktor Gyökeres', 'Suecia', 'SWE', 'Suecia', 8, 'jugador', 'normal', 487),
(489, 'SWE9', 'Robin Olsen', 'Suecia', 'SWE', 'Suecia', 9, 'jugador', 'normal', 488),
(490, 'SWE10', 'Linus Wahlqvist', 'Suecia', 'SWE', 'Suecia', 10, 'jugador', 'shiny', 489),
(491, 'SWE11', 'Gustav Berggren', 'Suecia', 'SWE', 'Suecia', 11, 'jugador', 'normal', 490),
(492, 'SWE12', 'Albin Ekdal', 'Suecia', 'SWE', 'Suecia', 12, 'jugador', 'normal', 491),
(493, 'SWE13', 'Foto de equipo', 'Suecia', 'SWE', 'Suecia', 13, 'foto_equipo', 'special', 492),
(494, 'SWE14', 'Filip Helander', 'Suecia', 'SWE', 'Suecia', 14, 'jugador', 'normal', 493),
(495, 'SWE15', 'Mattias Johansson', 'Suecia', 'SWE', 'Suecia', 15, 'jugador', 'shiny', 494),
(496, 'SWE16', 'Simon Olsson', 'Suecia', 'SWE', 'Suecia', 16, 'jugador', 'normal', 495),
(497, 'SWE17', 'Carl Starfelt', 'Suecia', 'SWE', 'Suecia', 17, 'jugador', 'shiny', 496),
(498, 'SWE18', 'Kristoffer Olsson', 'Suecia', 'SWE', 'Suecia', 18, 'jugador', 'normal', 497),
(499, 'SWE19', 'Isak Andri Sigurgeirsson', 'Suecia', 'SWE', 'Suecia', 19, 'jugador', 'normal', 498),
(500, 'SWE20', 'Willy Semedo', 'Suecia', 'SWE', 'Suecia', 20, 'jugador', 'normal', 499),
(501, 'BEL1', 'Escudo Bélgica', 'Bélgica', 'BEL', 'Bélgica', 1, 'escudo', 'shiny', 500),
(502, 'BEL2', 'Koen Casteels', 'Bélgica', 'BEL', 'Bélgica', 2, 'jugador', 'normal', 501),
(503, 'BEL3', 'Timothy Castagne', 'Bélgica', 'BEL', 'Bélgica', 3, 'jugador', 'normal', 502),
(504, 'BEL4', 'Wout Faes', 'Bélgica', 'BEL', 'Bélgica', 4, 'jugador', 'normal', 503),
(505, 'BEL5', 'Arthur Theate', 'Bélgica', 'BEL', 'Bélgica', 5, 'jugador', 'normal', 504),
(506, 'BEL6', 'Yannick Carrasco', 'Bélgica', 'BEL', 'Bélgica', 6, 'jugador', 'normal', 505),
(507, 'BEL7', 'Kevin De Bruyne', 'Bélgica', 'BEL', 'Bélgica', 7, 'jugador', 'normal', 506),
(508, 'BEL8', 'Youri Tielemans', 'Bélgica', 'BEL', 'Bélgica', 8, 'jugador', 'normal', 507),
(509, 'BEL9', 'Amadou Onana', 'Bélgica', 'BEL', 'Bélgica', 9, 'jugador', 'normal', 508),
(510, 'BEL10', 'Jeremy Doku', 'Bélgica', 'BEL', 'Bélgica', 10, 'jugador', 'shiny', 509),
(511, 'BEL11', 'Romelu Lukaku', 'Bélgica', 'BEL', 'Bélgica', 11, 'jugador', 'normal', 510),
(512, 'BEL12', 'Loïs Openda', 'Bélgica', 'BEL', 'Bélgica', 12, 'jugador', 'normal', 511),
(513, 'BEL13', 'Foto de equipo', 'Bélgica', 'BEL', 'Bélgica', 13, 'foto_equipo', 'special', 512),
(514, 'BEL14', 'Charles De Ketelaere', 'Bélgica', 'BEL', 'Bélgica', 14, 'jugador', 'normal', 513),
(515, 'BEL15', 'Leandro Trossard', 'Bélgica', 'BEL', 'Bélgica', 15, 'jugador', 'shiny', 514),
(516, 'BEL16', 'Dodi Lukebakio', 'Bélgica', 'BEL', 'Bélgica', 16, 'jugador', 'normal', 515),
(517, 'BEL17', 'Thomas Meunier', 'Bélgica', 'BEL', 'Bélgica', 17, 'jugador', 'shiny', 516),
(518, 'BEL18', 'Axel Witsel', 'Bélgica', 'BEL', 'Bélgica', 18, 'jugador', 'normal', 517),
(519, 'BEL19', 'Thibaut Courtois', 'Bélgica', 'BEL', 'Bélgica', 19, 'jugador', 'normal', 518),
(520, 'BEL20', 'Jérémy Doku', 'Bélgica', 'BEL', 'Bélgica', 20, 'jugador', 'normal', 519),
(521, 'IRN1', 'Escudo Irán', 'Irán', 'IRN', 'Irán', 1, 'escudo', 'shiny', 520),
(522, 'IRN2', 'Alireza Beiranvand', 'Irán', 'IRN', 'Irán', 2, 'jugador', 'normal', 521),
(523, 'IRN3', 'Sardar Azmoun', 'Irán', 'IRN', 'Irán', 3, 'jugador', 'normal', 522),
(524, 'IRN4', 'Mehdi Taremi', 'Irán', 'IRN', 'Irán', 4, 'jugador', 'normal', 523),
(525, 'IRN5', 'Saeid Ezatolahi', 'Irán', 'IRN', 'Irán', 5, 'jugador', 'normal', 524),
(526, 'IRN6', 'Milad Mohammadi', 'Irán', 'IRN', 'Irán', 6, 'jugador', 'normal', 525),
(527, 'IRN7', 'Ehsan Hajsafi', 'Irán', 'IRN', 'Irán', 7, 'jugador', 'normal', 526),
(528, 'IRN8', 'Alireza Jahanbakhsh', 'Irán', 'IRN', 'Irán', 8, 'jugador', 'normal', 527),
(529, 'IRN9', 'Karim Ansarifard', 'Irán', 'IRN', 'Irán', 9, 'jugador', 'normal', 528),
(530, 'IRN10', 'Rouzbeh Cheshmi', 'Irán', 'IRN', 'Irán', 10, 'jugador', 'shiny', 529),
(531, 'IRN11', 'Shojae Khalilzadeh', 'Irán', 'IRN', 'Irán', 11, 'jugador', 'normal', 530),
(532, 'IRN12', 'Vahid Amiri', 'Irán', 'IRN', 'Irán', 12, 'jugador', 'normal', 531),
(533, 'IRN13', 'Foto de equipo', 'Irán', 'IRN', 'Irán', 13, 'foto_equipo', 'special', 532),
(534, 'IRN14', 'Hossein Kanani', 'Irán', 'IRN', 'Irán', 14, 'jugador', 'normal', 533),
(535, 'IRN15', 'Saman Ghoddos', 'Irán', 'IRN', 'Irán', 15, 'jugador', 'shiny', 534),
(536, 'IRN16', 'Omid Noorafkan', 'Irán', 'IRN', 'Irán', 16, 'jugador', 'normal', 535),
(537, 'IRN17', 'Abolfazl Jalali', 'Irán', 'IRN', 'Irán', 17, 'jugador', 'shiny', 536),
(538, 'IRN18', 'Mohammad Mohebi', 'Irán', 'IRN', 'Irán', 18, 'jugador', 'normal', 537),
(539, 'IRN19', 'Payam Sadeghian', 'Irán', 'IRN', 'Irán', 19, 'jugador', 'normal', 538),
(540, 'IRN20', 'Amir Abedzadeh', 'Irán', 'IRN', 'Irán', 20, 'jugador', 'normal', 539),
(541, 'EGY1', 'Escudo Egipto', 'Egipto', 'EGY', 'Egipto', 1, 'escudo', 'shiny', 540),
(542, 'EGY2', 'Mohamed Salah', 'Egipto', 'EGY', 'Egipto', 2, 'jugador', 'normal', 541),
(543, 'EGY3', 'Mohamed El Shenawy', 'Egipto', 'EGY', 'Egipto', 3, 'jugador', 'normal', 542),
(544, 'EGY4', 'Mohamed Elneny', 'Egipto', 'EGY', 'Egipto', 4, 'jugador', 'normal', 543),
(545, 'EGY5', 'Ahmed Hegazi', 'Egipto', 'EGY', 'Egipto', 5, 'jugador', 'normal', 544),
(546, 'EGY6', 'Mahmoud Trezeguet', 'Egipto', 'EGY', 'Egipto', 6, 'jugador', 'normal', 545),
(547, 'EGY7', 'Omar Marmoush', 'Egipto', 'EGY', 'Egipto', 7, 'jugador', 'normal', 546),
(548, 'EGY8', 'Mostafa Mohamed', 'Egipto', 'EGY', 'Egipto', 8, 'jugador', 'normal', 547),
(549, 'EGY9', 'Trézéguet', 'Egipto', 'EGY', 'Egipto', 9, 'jugador', 'normal', 548),
(550, 'EGY10', 'Mohamed Abdelmonem', 'Egipto', 'EGY', 'Egipto', 10, 'jugador', 'shiny', 549),
(551, 'EGY11', 'Ahmed Sayed Zizo', 'Egipto', 'EGY', 'Egipto', 11, 'jugador', 'normal', 550),
(552, 'EGY12', 'Marwan Hamdy', 'Egipto', 'EGY', 'Egipto', 12, 'jugador', 'normal', 551),
(553, 'EGY13', 'Foto de equipo', 'Egipto', 'EGY', 'Egipto', 13, 'foto_equipo', 'special', 552),
(554, 'EGY14', 'Emam Ashour', 'Egipto', 'EGY', 'Egipto', 14, 'jugador', 'normal', 553),
(555, 'EGY15', 'Ahmed Fatouh', 'Egipto', 'EGY', 'Egipto', 15, 'jugador', 'shiny', 554),
(556, 'EGY16', 'Mohamed Hany', 'Egipto', 'EGY', 'Egipto', 16, 'jugador', 'normal', 555),
(557, 'EGY17', 'Ayman Ashraf', 'Egipto', 'EGY', 'Egipto', 17, 'jugador', 'shiny', 556),
(558, 'EGY18', 'Mohamed Magdy', 'Egipto', 'EGY', 'Egipto', 18, 'jugador', 'normal', 557),
(559, 'EGY19', 'Karim Adel', 'Egipto', 'EGY', 'Egipto', 19, 'jugador', 'normal', 558),
(560, 'EGY20', 'Mohamed Sobhi', 'Egipto', 'EGY', 'Egipto', 20, 'jugador', 'normal', 559),
(561, 'NZL1', 'Escudo Nueva Zelanda', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 1, 'escudo', 'shiny', 560),
(562, 'NZL2', 'Chris Wood', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 2, 'jugador', 'normal', 561),
(563, 'NZL3', 'Winston Reid', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 3, 'jugador', 'normal', 562),
(564, 'NZL4', 'Ryan Thomas', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 4, 'jugador', 'normal', 563),
(565, 'NZL5', 'Marco Rojas', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 5, 'jugador', 'normal', 564),
(566, 'NZL6', 'Michael Boxall', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 6, 'jugador', 'normal', 565),
(567, 'NZL7', 'Tommy Smith', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 7, 'jugador', 'normal', 566),
(568, 'NZL8', 'Alex Rufer', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 8, 'jugador', 'normal', 567),
(569, 'NZL9', 'Marko Stamenic', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 9, 'jugador', 'normal', 568),
(570, 'NZL10', 'Ben Old', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 10, 'jugador', 'shiny', 569),
(571, 'NZL11', 'Elijah Just', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 11, 'jugador', 'normal', 570),
(572, 'NZL12', 'Justine Velapiano', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 12, 'jugador', 'normal', 571),
(573, 'NZL13', 'Foto de equipo', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 13, 'foto_equipo', 'special', 572),
(574, 'NZL14', 'Oli Sail', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 14, 'jugador', 'normal', 573),
(575, 'NZL15', 'Bill Tuiloma', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 15, 'jugador', 'shiny', 574),
(576, 'NZL16', 'Finn Conchie', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 16, 'jugador', 'normal', 575),
(577, 'NZL17', 'Joe Bell', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 17, 'jugador', 'shiny', 576),
(578, 'NZL18', 'Kosta Barbarouses', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 18, 'jugador', 'normal', 577),
(579, 'NZL19', 'Clayton Lewis', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 19, 'jugador', 'normal', 578),
(580, 'NZL20', 'Dane Ingham', 'Nueva Zelanda', 'NZL', 'Nueva Zelanda', 20, 'jugador', 'normal', 579),
(581, 'ESP1', 'Escudo España', 'España', 'ESP', 'España', 1, 'escudo', 'shiny', 580),
(582, 'ESP2', 'Unai Simón', 'España', 'ESP', 'España', 2, 'jugador', 'normal', 581),
(583, 'ESP3', 'Dani Carvajal', 'España', 'ESP', 'España', 3, 'jugador', 'normal', 582),
(584, 'ESP4', 'Aymeric Laporte', 'España', 'ESP', 'España', 4, 'jugador', 'normal', 583),
(585, 'ESP5', 'Robin Le Normand', 'España', 'ESP', 'España', 5, 'jugador', 'normal', 584),
(586, 'ESP6', 'Marc Cucurella', 'España', 'ESP', 'España', 6, 'jugador', 'normal', 585),
(587, 'ESP7', 'Rodri', 'España', 'ESP', 'España', 7, 'jugador', 'normal', 586),
(588, 'ESP8', 'Pedri', 'España', 'ESP', 'España', 8, 'jugador', 'normal', 587),
(589, 'ESP9', 'Gavi', 'España', 'ESP', 'España', 9, 'jugador', 'normal', 588),
(590, 'ESP10', 'Nico Williams', 'España', 'ESP', 'España', 10, 'jugador', 'shiny', 589),
(591, 'ESP11', 'Lamine Yamal', 'España', 'ESP', 'España', 11, 'jugador', 'normal', 590),
(592, 'ESP12', 'Álvaro Morata', 'España', 'ESP', 'España', 12, 'jugador', 'normal', 591),
(593, 'ESP13', 'Foto de equipo', 'España', 'ESP', 'España', 13, 'foto_equipo', 'special', 592),
(594, 'ESP14', 'Mikel Oyarzabal', 'España', 'ESP', 'España', 14, 'jugador', 'normal', 593),
(595, 'ESP15', 'Ferran Torres', 'España', 'ESP', 'España', 15, 'jugador', 'shiny', 594),
(596, 'ESP16', 'Dani Olmo', 'España', 'ESP', 'España', 16, 'jugador', 'normal', 595),
(597, 'ESP17', 'Fabián Ruiz', 'España', 'ESP', 'España', 17, 'jugador', 'shiny', 596),
(598, 'ESP18', 'Alejandro Balde', 'España', 'ESP', 'España', 18, 'jugador', 'normal', 597),
(599, 'ESP19', 'Pau Cubarsí', 'España', 'ESP', 'España', 19, 'jugador', 'normal', 598),
(600, 'ESP20', 'Nico González', 'España', 'ESP', 'España', 20, 'jugador', 'normal', 599),
(601, 'URU1', 'Escudo Uruguay', 'Uruguay', 'URU', 'Uruguay', 1, 'escudo', 'shiny', 600),
(602, 'URU2', 'Sergio Rochet', 'Uruguay', 'URU', 'Uruguay', 2, 'jugador', 'normal', 601),
(603, 'URU3', 'Ronald Araújo', 'Uruguay', 'URU', 'Uruguay', 3, 'jugador', 'normal', 602),
(604, 'URU4', 'José Giménez', 'Uruguay', 'URU', 'Uruguay', 4, 'jugador', 'normal', 603),
(605, 'URU5', 'Sebastián Coates', 'Uruguay', 'URU', 'Uruguay', 5, 'jugador', 'normal', 604),
(606, 'URU6', 'Matías Viña', 'Uruguay', 'URU', 'Uruguay', 6, 'jugador', 'normal', 605),
(607, 'URU7', 'Manuel Ugarte', 'Uruguay', 'URU', 'Uruguay', 7, 'jugador', 'normal', 606),
(608, 'URU8', 'Federico Valverde', 'Uruguay', 'URU', 'Uruguay', 8, 'jugador', 'normal', 607),
(609, 'URU9', 'Rodrigo Bentancur', 'Uruguay', 'URU', 'Uruguay', 9, 'jugador', 'normal', 608),
(610, 'URU10', 'Giorgian De Arrascaeta', 'Uruguay', 'URU', 'Uruguay', 10, 'jugador', 'shiny', 609),
(611, 'URU11', 'Darwin Núñez', 'Uruguay', 'URU', 'Uruguay', 11, 'jugador', 'normal', 610),
(612, 'URU12', 'Facundo Pellistri', 'Uruguay', 'URU', 'Uruguay', 12, 'jugador', 'normal', 611),
(613, 'URU13', 'Foto de equipo', 'Uruguay', 'URU', 'Uruguay', 13, 'foto_equipo', 'special', 612),
(614, 'URU14', 'Luis Suárez', 'Uruguay', 'URU', 'Uruguay', 14, 'jugador', 'normal', 613),
(615, 'URU15', 'Maxi Gómez', 'Uruguay', 'URU', 'Uruguay', 15, 'jugador', 'shiny', 614),
(616, 'URU16', 'Nicolás de la Cruz', 'Uruguay', 'URU', 'Uruguay', 16, 'jugador', 'normal', 615),
(617, 'URU17', 'Matías Vecino', 'Uruguay', 'URU', 'Uruguay', 17, 'jugador', 'shiny', 616),
(618, 'URU18', 'Brian Rodríguez', 'Uruguay', 'URU', 'Uruguay', 18, 'jugador', 'normal', 617),
(619, 'URU19', 'Agustín Oliveros', 'Uruguay', 'URU', 'Uruguay', 19, 'jugador', 'normal', 618),
(620, 'URU20', 'Santiago Bueno', 'Uruguay', 'URU', 'Uruguay', 20, 'jugador', 'normal', 619),
(621, 'KSA1', 'Escudo Arabia Saudita', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 1, 'escudo', 'shiny', 620),
(622, 'KSA2', 'Mohammed Al-Owais', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 2, 'jugador', 'normal', 621),
(623, 'KSA3', 'Salem Al-Dawsari', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 3, 'jugador', 'normal', 622),
(624, 'KSA4', 'Firas Al-Buraikan', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 4, 'jugador', 'normal', 623),
(625, 'KSA5', 'Saud Abdulhamid', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 5, 'jugador', 'normal', 624),
(626, 'KSA6', 'Mohammed Kanno', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 6, 'jugador', 'normal', 625),
(627, 'KSA7', 'Abdulellah Al-Malki', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 7, 'jugador', 'normal', 626),
(628, 'KSA8', 'Saleh Al-Shehri', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 8, 'jugador', 'normal', 627),
(629, 'KSA9', 'Yasser Al-Shahrani', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 9, 'jugador', 'normal', 628),
(630, 'KSA10', 'Ali Al-Bulaihi', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 10, 'jugador', 'shiny', 629),
(631, 'KSA11', 'Sami Al-Najei', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 11, 'jugador', 'normal', 630),
(632, 'KSA12', 'Nasser Al-Dawsari', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 12, 'jugador', 'normal', 631),
(633, 'KSA13', 'Foto de equipo', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 13, 'foto_equipo', 'special', 632),
(634, 'KSA14', 'Hassan Al-Tambakti', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 14, 'jugador', 'normal', 633),
(635, 'KSA15', 'Mohammed Al-Burayk', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 15, 'jugador', 'shiny', 634),
(636, 'KSA16', 'Ayman Yahya', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 16, 'jugador', 'normal', 635),
(637, 'KSA17', 'Fahad Al-Muwallad', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 17, 'jugador', 'shiny', 636),
(638, 'KSA18', 'Sultan Al-Ghannam', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 18, 'jugador', 'normal', 637),
(639, 'KSA19', 'Abdullah Al-Mayouf', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 19, 'jugador', 'normal', 638),
(640, 'KSA20', 'Nawaf Al-Abed', 'Arabia Saudita', 'KSA', 'Arabia Saudita', 20, 'jugador', 'normal', 639),
(641, 'CPV1', 'Escudo Cabo Verde', 'Cabo Verde', 'CPV', 'Cabo Verde', 1, 'escudo', 'shiny', 640),
(642, 'CPV2', 'Ryan Mendes', 'Cabo Verde', 'CPV', 'Cabo Verde', 2, 'jugador', 'normal', 641),
(643, 'CPV3', 'Jovane Cabral', 'Cabo Verde', 'CPV', 'Cabo Verde', 3, 'jugador', 'normal', 642),
(644, 'CPV4', 'Djaniny', 'Cabo Verde', 'CPV', 'Cabo Verde', 4, 'jugador', 'normal', 643),
(645, 'CPV5', 'Stopira', 'Cabo Verde', 'CPV', 'Cabo Verde', 5, 'jugador', 'normal', 644),
(646, 'CPV6', 'Garry Rodrigues', 'Cabo Verde', 'CPV', 'Cabo Verde', 6, 'jugador', 'normal', 645),
(647, 'CPV7', 'Babanco', 'Cabo Verde', 'CPV', 'Cabo Verde', 7, 'jugador', 'normal', 646),
(648, 'CPV8', 'Marco Soares', 'Cabo Verde', 'CPV', 'Cabo Verde', 8, 'jugador', 'normal', 647),
(649, 'CPV9', 'Vozinha', 'Cabo Verde', 'CPV', 'Cabo Verde', 9, 'jugador', 'normal', 648),
(650, 'CPV10', 'Steve Furtado', 'Cabo Verde', 'CPV', 'Cabo Verde', 10, 'jugador', 'shiny', 649),
(651, 'CPV11', 'Patrick Andrade', 'Cabo Verde', 'CPV', 'Cabo Verde', 11, 'jugador', 'normal', 650),
(652, 'CPV12', 'Jamiro Monteiro', 'Cabo Verde', 'CPV', 'Cabo Verde', 12, 'jugador', 'normal', 651),
(653, 'CPV13', 'Foto de equipo', 'Cabo Verde', 'CPV', 'Cabo Verde', 13, 'foto_equipo', 'special', 652),
(654, 'CPV14', 'Kelvin Pires', 'Cabo Verde', 'CPV', 'Cabo Verde', 14, 'jugador', 'normal', 653),
(655, 'CPV15', 'Kenny Rocha Santos', 'Cabo Verde', 'CPV', 'Cabo Verde', 15, 'jugador', 'shiny', 654),
(656, 'CPV16', 'Bebé', 'Cabo Verde', 'CPV', 'Cabo Verde', 16, 'jugador', 'normal', 655),
(657, 'CPV17', 'Bruno Leite', 'Cabo Verde', 'CPV', 'Cabo Verde', 17, 'jugador', 'shiny', 656),
(658, 'CPV18', 'Carlos Ponck', 'Cabo Verde', 'CPV', 'Cabo Verde', 18, 'jugador', 'normal', 657),
(659, 'CPV19', 'Diney', 'Cabo Verde', 'CPV', 'Cabo Verde', 19, 'jugador', 'normal', 658),
(660, 'CPV20', 'Dyego Andrade', 'Cabo Verde', 'CPV', 'Cabo Verde', 20, 'jugador', 'normal', 659),
(661, 'FRA1', 'Escudo Francia', 'Francia', 'FRA', 'Francia', 1, 'escudo', 'shiny', 660),
(662, 'FRA2', 'Mike Maignan', 'Francia', 'FRA', 'Francia', 2, 'jugador', 'normal', 661),
(663, 'FRA3', 'Jules Koundé', 'Francia', 'FRA', 'Francia', 3, 'jugador', 'normal', 662),
(664, 'FRA4', 'William Saliba', 'Francia', 'FRA', 'Francia', 4, 'jugador', 'normal', 663),
(665, 'FRA5', 'Dayot Upamecano', 'Francia', 'FRA', 'Francia', 5, 'jugador', 'normal', 664),
(666, 'FRA6', 'Théo Hernandez', 'Francia', 'FRA', 'Francia', 6, 'jugador', 'normal', 665),
(667, 'FRA7', 'Aurélien Tchouaméni', 'Francia', 'FRA', 'Francia', 7, 'jugador', 'normal', 666),
(668, 'FRA8', 'N''Golo Kanté', 'Francia', 'FRA', 'Francia', 8, 'jugador', 'normal', 667),
(669, 'FRA9', 'Adrien Rabbio', 'Francia', 'FRA', 'Francia', 9, 'jugador', 'normal', 668),
(670, 'FRA10', 'Ousmane Dembélé', 'Francia', 'FRA', 'Francia', 10, 'jugador', 'shiny', 669),
(671, 'FRA11', 'Kylian Mbappé', 'Francia', 'FRA', 'Francia', 11, 'jugador', 'normal', 670),
(672, 'FRA12', 'Antoine Griezmann', 'Francia', 'FRA', 'Francia', 12, 'jugador', 'normal', 671),
(673, 'FRA13', 'Foto de equipo', 'Francia', 'FRA', 'Francia', 13, 'foto_equipo', 'special', 672),
(674, 'FRA14', 'Olivier Giroud', 'Francia', 'FRA', 'Francia', 14, 'jugador', 'normal', 673),
(675, 'FRA15', 'Kingsley Coman', 'Francia', 'FRA', 'Francia', 15, 'jugador', 'shiny', 674),
(676, 'FRA16', 'Randal Kolo Muani', 'Francia', 'FRA', 'Francia', 16, 'jugador', 'normal', 675),
(677, 'FRA17', 'Ibrahima Konaté', 'Francia', 'FRA', 'Francia', 17, 'jugador', 'shiny', 676),
(678, 'FRA18', 'Marcus Thuram', 'Francia', 'FRA', 'Francia', 18, 'jugador', 'normal', 677),
(679, 'FRA19', 'Youssouf Fofana', 'Francia', 'FRA', 'Francia', 19, 'jugador', 'normal', 678),
(680, 'FRA20', 'Warren Zaïre-Emery', 'Francia', 'FRA', 'Francia', 20, 'jugador', 'normal', 679),
(681, 'SEN1', 'Escudo Senegal', 'Senegal', 'SEN', 'Senegal', 1, 'escudo', 'shiny', 680),
(682, 'SEN2', 'Edouard Mendy', 'Senegal', 'SEN', 'Senegal', 2, 'jugador', 'normal', 681),
(683, 'SEN3', 'Kalidou Koulibaly', 'Senegal', 'SEN', 'Senegal', 3, 'jugador', 'normal', 682),
(684, 'SEN4', 'Ismaïla Sarr', 'Senegal', 'SEN', 'Senegal', 4, 'jugador', 'normal', 683),
(685, 'SEN5', 'Sadio Mané', 'Senegal', 'SEN', 'Senegal', 5, 'jugador', 'normal', 684),
(686, 'SEN6', 'Idrissa Gueye', 'Senegal', 'SEN', 'Senegal', 6, 'jugador', 'normal', 685),
(687, 'SEN7', 'Pape Matar Sarr', 'Senegal', 'SEN', 'Senegal', 7, 'jugador', 'normal', 686),
(688, 'SEN8', 'Nicolas Jackson', 'Senegal', 'SEN', 'Senegal', 8, 'jugador', 'normal', 687),
(689, 'SEN9', 'Boulaye Dia', 'Senegal', 'SEN', 'Senegal', 9, 'jugador', 'normal', 688),
(690, 'SEN10', 'Formose Mendy', 'Senegal', 'SEN', 'Senegal', 10, 'jugador', 'shiny', 689),
(691, 'SEN11', 'Fodé Ballo-Touré', 'Senegal', 'SEN', 'Senegal', 11, 'jugador', 'normal', 690),
(692, 'SEN12', 'Pape Gueye', 'Senegal', 'SEN', 'Senegal', 12, 'jugador', 'normal', 691),
(693, 'SEN13', 'Foto de equipo', 'Senegal', 'SEN', 'Senegal', 13, 'foto_equipo', 'special', 692),
(694, 'SEN14', 'Moussa Niakhaté', 'Senegal', 'SEN', 'Senegal', 14, 'jugador', 'normal', 693),
(695, 'SEN15', 'Abdou Diallo', 'Senegal', 'SEN', 'Senegal', 15, 'jugador', 'shiny', 694),
(696, 'SEN16', 'Cheikh Kouyaté', 'Senegal', 'SEN', 'Senegal', 16, 'jugador', 'normal', 695),
(697, 'SEN17', 'Iliman Ndiaye', 'Senegal', 'SEN', 'Senegal', 17, 'jugador', 'shiny', 696),
(698, 'SEN18', 'Moussa Sarr', 'Senegal', 'SEN', 'Senegal', 18, 'jugador', 'normal', 697),
(699, 'SEN19', 'Pathé Ciss', 'Senegal', 'SEN', 'Senegal', 19, 'jugador', 'normal', 698),
(700, 'SEN20', 'Mamadou Lamine Camara', 'Senegal', 'SEN', 'Senegal', 20, 'jugador', 'normal', 699),
(701, 'NOR1', 'Escudo Noruega', 'Noruega', 'NOR', 'Noruega', 1, 'escudo', 'shiny', 700),
(702, 'NOR2', 'Erling Haaland', 'Noruega', 'NOR', 'Noruega', 2, 'jugador', 'normal', 701),
(703, 'NOR3', 'Martin Ødegaard', 'Noruega', 'NOR', 'Noruega', 3, 'jugador', 'normal', 702),
(704, 'NOR4', 'Alexander Sørloth', 'Noruega', 'NOR', 'Noruega', 4, 'jugador', 'normal', 703),
(705, 'NOR5', 'Sander Berge', 'Noruega', 'NOR', 'Noruega', 5, 'jugador', 'normal', 704),
(706, 'NOR6', 'Fredrik Aursnes', 'Noruega', 'NOR', 'Noruega', 6, 'jugador', 'normal', 705),
(707, 'NOR7', 'Kristoffer Ajer', 'Noruega', 'NOR', 'Noruega', 7, 'jugador', 'normal', 706),
(708, 'NOR8', 'Felix Myhre', 'Noruega', 'NOR', 'Noruega', 8, 'jugador', 'normal', 707),
(709, 'NOR9', 'Antonio Nusa', 'Noruega', 'NOR', 'Noruega', 9, 'jugador', 'normal', 708),
(710, 'NOR10', 'Aron Dønnum', 'Noruega', 'NOR', 'Noruega', 10, 'jugador', 'shiny', 709),
(711, 'NOR11', 'Patrick Berg', 'Noruega', 'NOR', 'Noruega', 11, 'jugador', 'normal', 710),
(712, 'NOR12', 'Leo Østigård', 'Noruega', 'NOR', 'Noruega', 12, 'jugador', 'normal', 711),
(713, 'NOR13', 'Foto de equipo', 'Noruega', 'NOR', 'Noruega', 13, 'foto_equipo', 'special', 712),
(714, 'NOR14', 'Mattias Moström', 'Noruega', 'NOR', 'Noruega', 14, 'jugador', 'normal', 713),
(715, 'NOR15', 'Julian Ryerson', 'Noruega', 'NOR', 'Noruega', 15, 'jugador', 'shiny', 714),
(716, 'NOR16', 'Håkon Evjen', 'Noruega', 'NOR', 'Noruega', 16, 'jugador', 'normal', 715),
(717, 'NOR17', 'Ola Solbakken', 'Noruega', 'NOR', 'Noruega', 17, 'jugador', 'shiny', 716),
(718, 'NOR18', 'André Hansen', 'Noruega', 'NOR', 'Noruega', 18, 'jugador', 'normal', 717),
(719, 'NOR19', 'Stian Gregersen', 'Noruega', 'NOR', 'Noruega', 19, 'jugador', 'normal', 718),
(720, 'NOR20', 'Morten Thorsby', 'Noruega', 'NOR', 'Noruega', 20, 'jugador', 'normal', 719),
(721, 'IRQ1', 'Escudo Irak', 'Irak', 'IRQ', 'Irak', 1, 'escudo', 'shiny', 720),
(722, 'IRQ2', 'Mohammed Al-Debek', 'Irak', 'IRQ', 'Irak', 2, 'jugador', 'normal', 721),
(723, 'IRQ3', 'Ahmad Ibrahim', 'Irak', 'IRQ', 'Irak', 3, 'jugador', 'normal', 722),
(724, 'IRQ4', 'Ali Adnan', 'Irak', 'IRQ', 'Irak', 4, 'jugador', 'normal', 723),
(725, 'IRQ5', 'Humam Tariq', 'Irak', 'IRQ', 'Irak', 5, 'jugador', 'normal', 724),
(726, 'IRQ6', 'Mohanad Ali', 'Irak', 'IRQ', 'Irak', 6, 'jugador', 'normal', 725),
(727, 'IRQ7', 'Amjad Attwan', 'Irak', 'IRQ', 'Irak', 7, 'jugador', 'normal', 726),
(728, 'IRQ8', 'Bashar Resan', 'Irak', 'IRQ', 'Irak', 8, 'jugador', 'normal', 727),
(729, 'IRQ9', 'Ali Faez', 'Irak', 'IRQ', 'Irak', 9, 'jugador', 'normal', 728),
(730, 'IRQ10', 'Manar Salih', 'Irak', 'IRQ', 'Irak', 10, 'jugador', 'shiny', 729),
(731, 'IRQ11', 'Saad Natiq', 'Irak', 'IRQ', 'Irak', 11, 'jugador', 'normal', 730),
(732, 'IRQ12', 'Alaa Abdul-Zahra', 'Irak', 'IRQ', 'Irak', 12, 'jugador', 'normal', 731),
(733, 'IRQ13', 'Foto de equipo', 'Irak', 'IRQ', 'Irak', 13, 'foto_equipo', 'special', 732),
(734, 'IRQ14', 'Ahmed Yasin', 'Irak', 'IRQ', 'Irak', 14, 'jugador', 'normal', 733),
(735, 'IRQ15', 'Dhurgham Ismail', 'Irak', 'IRQ', 'Irak', 15, 'jugador', 'shiny', 734),
(736, 'IRQ16', 'Mustafa Saad', 'Irak', 'IRQ', 'Irak', 16, 'jugador', 'normal', 735),
(737, 'IRQ17', 'Osama Rashid', 'Irak', 'IRQ', 'Irak', 17, 'jugador', 'shiny', 736),
(738, 'IRQ18', 'Hussein Ali', 'Irak', 'IRQ', 'Irak', 18, 'jugador', 'normal', 737),
(739, 'IRQ19', 'Ahmed Al-Saadi', 'Irak', 'IRQ', 'Irak', 19, 'jugador', 'normal', 738),
(740, 'IRQ20', 'Jalal Hassan', 'Irak', 'IRQ', 'Irak', 20, 'jugador', 'normal', 739),
(741, 'ARG1', 'Escudo Argentina', 'Argentina', 'ARG', 'Argentina', 1, 'escudo', 'shiny', 740),
(742, 'ARG2', 'Emiliano Martínez', 'Argentina', 'ARG', 'Argentina', 2, 'jugador', 'normal', 741),
(743, 'ARG3', 'Cristian Romero', 'Argentina', 'ARG', 'Argentina', 3, 'jugador', 'normal', 742),
(744, 'ARG4', 'Nicolás Otamendi', 'Argentina', 'ARG', 'Argentina', 4, 'jugador', 'normal', 743),
(745, 'ARG5', 'Marcos Acuña', 'Argentina', 'ARG', 'Argentina', 5, 'jugador', 'normal', 744),
(746, 'ARG6', 'Gonzalo Montiel', 'Argentina', 'ARG', 'Argentina', 6, 'jugador', 'normal', 745),
(747, 'ARG7', 'Leandro Paredes', 'Argentina', 'ARG', 'Argentina', 7, 'jugador', 'normal', 746),
(748, 'ARG8', 'Rodrigo De Paul', 'Argentina', 'ARG', 'Argentina', 8, 'jugador', 'normal', 747),
(749, 'ARG9', 'Enzo Fernández', 'Argentina', 'ARG', 'Argentina', 9, 'jugador', 'normal', 748),
(750, 'ARG10', 'Alexis Mac Allister', 'Argentina', 'ARG', 'Argentina', 10, 'jugador', 'shiny', 749),
(751, 'ARG11', 'Ángel Di María', 'Argentina', 'ARG', 'Argentina', 11, 'jugador', 'normal', 750),
(752, 'ARG12', 'Lautaro Martínez', 'Argentina', 'ARG', 'Argentina', 12, 'jugador', 'normal', 751),
(753, 'ARG13', 'Foto de equipo', 'Argentina', 'ARG', 'Argentina', 13, 'foto_equipo', 'special', 752),
(754, 'ARG14', 'Julián Álvarez', 'Argentina', 'ARG', 'Argentina', 14, 'jugador', 'normal', 753),
(755, 'ARG15', 'Nicolás González', 'Argentina', 'ARG', 'Argentina', 15, 'jugador', 'shiny', 754),
(756, 'ARG16', 'Paulo Dybala', 'Argentina', 'ARG', 'Argentina', 16, 'jugador', 'normal', 755),
(757, 'ARG17', 'Giovani Lo Celso', 'Argentina', 'ARG', 'Argentina', 17, 'jugador', 'shiny', 756),
(758, 'ARG18', 'Lisandro Martínez', 'Argentina', 'ARG', 'Argentina', 18, 'jugador', 'normal', 757),
(759, 'ARG19', 'Exequiel Palacios', 'Argentina', 'ARG', 'Argentina', 19, 'jugador', 'normal', 758),
(760, 'ARG20', 'Germán Pezzella', 'Argentina', 'ARG', 'Argentina', 20, 'jugador', 'normal', 759),
(761, 'AUT1', 'Escudo Austria', 'Austria', 'AUT', 'Austria', 1, 'escudo', 'shiny', 760),
(762, 'AUT2', 'David Alaba', 'Austria', 'AUT', 'Austria', 2, 'jugador', 'normal', 761),
(763, 'AUT3', 'Marcel Sabitzer', 'Austria', 'AUT', 'Austria', 3, 'jugador', 'normal', 762),
(764, 'AUT4', 'Konrad Laimer', 'Austria', 'AUT', 'Austria', 4, 'jugador', 'normal', 763),
(765, 'AUT5', 'Florian Grillitsch', 'Austria', 'AUT', 'Austria', 5, 'jugador', 'normal', 764),
(766, 'AUT6', 'Christoph Baumgartner', 'Austria', 'AUT', 'Austria', 6, 'jugador', 'normal', 765),
(767, 'AUT7', 'Marko Arnautović', 'Austria', 'AUT', 'Austria', 7, 'jugador', 'normal', 766),
(768, 'AUT8', 'Michael Gregoritsch', 'Austria', 'AUT', 'Austria', 8, 'jugador', 'normal', 767),
(769, 'AUT9', 'Romano Schmid', 'Austria', 'AUT', 'Austria', 9, 'jugador', 'normal', 768),
(770, 'AUT10', 'Philipp Lienhart', 'Austria', 'AUT', 'Austria', 10, 'jugador', 'shiny', 769),
(771, 'AUT11', 'Stefan Posch', 'Austria', 'AUT', 'Austria', 11, 'jugador', 'normal', 770),
(772, 'AUT12', 'Patrick Wimmer', 'Austria', 'AUT', 'Austria', 12, 'jugador', 'normal', 771),
(773, 'AUT13', 'Foto de equipo', 'Austria', 'AUT', 'Austria', 13, 'foto_equipo', 'special', 772),
(774, 'AUT14', 'Alexander Schlager', 'Austria', 'AUT', 'Austria', 14, 'jugador', 'normal', 773),
(775, 'AUT15', 'Philipp Mwene', 'Austria', 'AUT', 'Austria', 15, 'jugador', 'shiny', 774),
(776, 'AUT16', 'Gernot Trauner', 'Austria', 'AUT', 'Austria', 16, 'jugador', 'normal', 775),
(777, 'AUT17', 'Marco Friedl', 'Austria', 'AUT', 'Austria', 17, 'jugador', 'shiny', 776),
(778, 'AUT18', 'Andreas Ulmer', 'Austria', 'AUT', 'Austria', 18, 'jugador', 'normal', 777),
(779, 'AUT19', 'Nicolas Seiwald', 'Austria', 'AUT', 'Austria', 19, 'jugador', 'normal', 778),
(780, 'AUT20', 'Yannick Gerhardt', 'Austria', 'AUT', 'Austria', 20, 'jugador', 'normal', 779),
(781, 'ALG1', 'Escudo Argelia', 'Argelia', 'ALG', 'Argelia', 1, 'escudo', 'shiny', 780),
(782, 'ALG2', 'Riyad Mahrez', 'Argelia', 'ALG', 'Argelia', 2, 'jugador', 'normal', 781),
(783, 'ALG3', 'Ismaël Bennacer', 'Argelia', 'ALG', 'Argelia', 3, 'jugador', 'normal', 782),
(784, 'ALG4', 'Youcef Atal', 'Argelia', 'ALG', 'Argelia', 4, 'jugador', 'normal', 783),
(785, 'ALG5', 'Ramy Bensebaini', 'Argelia', 'ALG', 'Argelia', 5, 'jugador', 'normal', 784),
(786, 'ALG6', 'Aïssa Mandi', 'Argelia', 'ALG', 'Argelia', 6, 'jugador', 'normal', 785),
(787, 'ALG7', 'Haris Belkebla', 'Argelia', 'ALG', 'Argelia', 7, 'jugador', 'normal', 786),
(788, 'ALG8', 'Adam Ounas', 'Argelia', 'ALG', 'Argelia', 8, 'jugador', 'normal', 787),
(789, 'ALG9', 'Baghdad Bounedjah', 'Argelia', 'ALG', 'Argelia', 9, 'jugador', 'normal', 788),
(790, 'ALG10', 'Youcef Belaïli', 'Argelia', 'ALG', 'Argelia', 10, 'jugador', 'shiny', 789),
(791, 'ALG11', 'Raïs M''Bolhi', 'Argelia', 'ALG', 'Argelia', 11, 'jugador', 'normal', 790),
(792, 'ALG12', 'Amine Gouiri', 'Argelia', 'ALG', 'Argelia', 12, 'jugador', 'normal', 791),
(793, 'ALG13', 'Foto de equipo', 'Argelia', 'ALG', 'Argelia', 13, 'foto_equipo', 'special', 792),
(794, 'ALG14', 'Sofiane Feghouli', 'Argelia', 'ALG', 'Argelia', 14, 'jugador', 'normal', 793),
(795, 'ALG15', 'Rachid Ghezzal', 'Argelia', 'ALG', 'Argelia', 15, 'jugador', 'shiny', 794),
(796, 'ALG16', 'Islam Slimani', 'Argelia', 'ALG', 'Argelia', 16, 'jugador', 'normal', 795),
(797, 'ALG17', 'Mohamed Amoura', 'Argelia', 'ALG', 'Argelia', 17, 'jugador', 'shiny', 796),
(798, 'ALG18', 'Hichem Boudaoui', 'Argelia', 'ALG', 'Argelia', 18, 'jugador', 'normal', 797),
(799, 'ALG19', 'Yacine Brahimi', 'Argelia', 'ALG', 'Argelia', 19, 'jugador', 'normal', 798),
(800, 'ALG20', 'Anthony Mandrea', 'Argelia', 'ALG', 'Argelia', 20, 'jugador', 'normal', 799),
(801, 'JOR1', 'Escudo Jordania', 'Jordania', 'JOR', 'Jordania', 1, 'escudo', 'shiny', 800),
(802, 'JOR2', 'Yaseen Al-Bakhit', 'Jordania', 'JOR', 'Jordania', 2, 'jugador', 'normal', 801),
(803, 'JOR3', 'Husam Abu-Seid', 'Jordania', 'JOR', 'Jordania', 3, 'jugador', 'normal', 802),
(804, 'JOR4', 'Mahmoud Al-Mardi', 'Jordania', 'JOR', 'Jordania', 4, 'jugador', 'normal', 803),
(805, 'JOR5', 'Ehsan Haddad', 'Jordania', 'JOR', 'Jordania', 5, 'jugador', 'normal', 804),
(806, 'JOR6', 'Yazan Al-Naimat', 'Jordania', 'JOR', 'Jordania', 6, 'jugador', 'normal', 805),
(807, 'JOR7', 'Musa Al-Taamari', 'Jordania', 'JOR', 'Jordania', 7, 'jugador', 'normal', 806),
(808, 'JOR8', 'Ali Olwan', 'Jordania', 'JOR', 'Jordania', 8, 'jugador', 'normal', 807),
(809, 'JOR9', 'Rajaei Ayed', 'Jordania', 'JOR', 'Jordania', 9, 'jugador', 'normal', 808),
(810, 'JOR10', 'Yazan Al-Arab', 'Jordania', 'JOR', 'Jordania', 10, 'jugador', 'shiny', 809),
(811, 'JOR11', 'Anas Bani Yaseen', 'Jordania', 'JOR', 'Jordania', 11, 'jugador', 'normal', 810),
(812, 'JOR12', 'Mohammad Abu Zraiq', 'Jordania', 'JOR', 'Jordania', 12, 'jugador', 'normal', 811),
(813, 'JOR13', 'Foto de equipo', 'Jordania', 'JOR', 'Jordania', 13, 'foto_equipo', 'special', 812),
(814, 'JOR14', 'Ihsan Haddad', 'Jordania', 'JOR', 'Jordania', 14, 'jugador', 'normal', 813),
(815, 'JOR15', 'Saleh Ratib', 'Jordania', 'JOR', 'Jordania', 15, 'jugador', 'shiny', 814),
(816, 'JOR16', 'Mohammad Al-Bataineh', 'Jordania', 'JOR', 'Jordania', 16, 'jugador', 'normal', 815),
(817, 'JOR17', 'Yazan Khattab', 'Jordania', 'JOR', 'Jordania', 17, 'jugador', 'shiny', 816),
(818, 'JOR18', 'Ahmad Ersan', 'Jordania', 'JOR', 'Jordania', 18, 'jugador', 'normal', 817),
(819, 'JOR19', 'Amjad Al-Hawamdeh', 'Jordania', 'JOR', 'Jordania', 19, 'jugador', 'normal', 818),
(820, 'JOR20', 'Abdallah Nasib', 'Jordania', 'JOR', 'Jordania', 20, 'jugador', 'normal', 819),
(821, 'POR1', 'Escudo Portugal', 'Portugal', 'POR', 'Portugal', 1, 'escudo', 'shiny', 820),
(822, 'POR2', 'Diogo Costa', 'Portugal', 'POR', 'Portugal', 2, 'jugador', 'normal', 821),
(823, 'POR3', 'João Cancelo', 'Portugal', 'POR', 'Portugal', 3, 'jugador', 'normal', 822),
(824, 'POR4', 'Rúben Dias', 'Portugal', 'POR', 'Portugal', 4, 'jugador', 'normal', 823),
(825, 'POR5', 'Pepe', 'Portugal', 'POR', 'Portugal', 5, 'jugador', 'normal', 824),
(826, 'POR6', 'Nuno Mendes', 'Portugal', 'POR', 'Portugal', 6, 'jugador', 'normal', 825),
(827, 'POR7', 'Bruno Fernandes', 'Portugal', 'POR', 'Portugal', 7, 'jugador', 'normal', 826),
(828, 'POR8', 'Bernardo Silva', 'Portugal', 'POR', 'Portugal', 8, 'jugador', 'normal', 827),
(829, 'POR9', 'Vitinha', 'Portugal', 'POR', 'Portugal', 9, 'jugador', 'normal', 828),
(830, 'POR10', 'Rafael Leão', 'Portugal', 'POR', 'Portugal', 10, 'jugador', 'shiny', 829),
(831, 'POR11', 'Cristiano Ronaldo', 'Portugal', 'POR', 'Portugal', 11, 'jugador', 'normal', 830),
(832, 'POR12', 'Diogo Jota', 'Portugal', 'POR', 'Portugal', 12, 'jugador', 'normal', 831),
(833, 'POR13', 'Foto de equipo', 'Portugal', 'POR', 'Portugal', 13, 'foto_equipo', 'special', 832),
(834, 'POR14', 'Gonçalo Ramos', 'Portugal', 'POR', 'Portugal', 14, 'jugador', 'normal', 833),
(835, 'POR15', 'Pedro Neto', 'Portugal', 'POR', 'Portugal', 15, 'jugador', 'shiny', 834),
(836, 'POR16', 'João Félix', 'Portugal', 'POR', 'Portugal', 16, 'jugador', 'normal', 835),
(837, 'POR17', 'Otávio', 'Portugal', 'POR', 'Portugal', 17, 'jugador', 'shiny', 836),
(838, 'POR18', 'Matheus Nunes', 'Portugal', 'POR', 'Portugal', 18, 'jugador', 'normal', 837),
(839, 'POR19', 'Danilo Pereira', 'Portugal', 'POR', 'Portugal', 19, 'jugador', 'normal', 838),
(840, 'POR20', 'Francisco Conceição', 'Portugal', 'POR', 'Portugal', 20, 'jugador', 'normal', 839),
(841, 'COL1', 'Escudo Colombia', 'Colombia', 'COL', 'Colombia', 1, 'escudo', 'shiny', 840),
(842, 'COL2', 'Camilo Vargas', 'Colombia', 'COL', 'Colombia', 2, 'jugador', 'normal', 841),
(843, 'COL3', 'Davinson Sánchez', 'Colombia', 'COL', 'Colombia', 3, 'jugador', 'normal', 842),
(844, 'COL4', 'Yerry Mina', 'Colombia', 'COL', 'Colombia', 4, 'jugador', 'normal', 843),
(845, 'COL5', 'Jhon Lucumí', 'Colombia', 'COL', 'Colombia', 5, 'jugador', 'normal', 844),
(846, 'COL6', 'Johan Mojica', 'Colombia', 'COL', 'Colombia', 6, 'jugador', 'normal', 845),
(847, 'COL7', 'Jefferson Lerma', 'Colombia', 'COL', 'Colombia', 7, 'jugador', 'normal', 846),
(848, 'COL8', 'Luis Díaz', 'Colombia', 'COL', 'Colombia', 8, 'jugador', 'normal', 847),
(849, 'COL9', 'James Rodríguez', 'Colombia', 'COL', 'Colombia', 9, 'jugador', 'normal', 848),
(850, 'COL10', 'Jhon Arias', 'Colombia', 'COL', 'Colombia', 10, 'jugador', 'shiny', 849),
(851, 'COL11', 'Luis Sinisterra', 'Colombia', 'COL', 'Colombia', 11, 'jugador', 'normal', 850),
(852, 'COL12', 'Rafael Santos Borré', 'Colombia', 'COL', 'Colombia', 12, 'jugador', 'normal', 851),
(853, 'COL13', 'Foto de equipo', 'Colombia', 'COL', 'Colombia', 13, 'foto_equipo', 'special', 852),
(854, 'COL14', 'Sebastián Villa', 'Colombia', 'COL', 'Colombia', 14, 'jugador', 'normal', 853),
(855, 'COL15', 'Yerson Mosquera', 'Colombia', 'COL', 'Colombia', 15, 'jugador', 'shiny', 854),
(856, 'COL16', 'Jhon Durán', 'Colombia', 'COL', 'Colombia', 16, 'jugador', 'normal', 855),
(857, 'COL17', 'Richard Ríos', 'Colombia', 'COL', 'Colombia', 17, 'jugador', 'shiny', 856),
(858, 'COL18', 'Daniel Muñoz', 'Colombia', 'COL', 'Colombia', 18, 'jugador', 'normal', 857),
(859, 'COL19', 'Kevin Castaño', 'Colombia', 'COL', 'Colombia', 19, 'jugador', 'normal', 858),
(860, 'COL20', 'Óscar Estupiñán', 'Colombia', 'COL', 'Colombia', 20, 'jugador', 'normal', 859),
(861, 'UZB1', 'Escudo Uzbekistán', 'Uzbekistán', 'UZB', 'Uzbekistán', 1, 'escudo', 'shiny', 860),
(862, 'UZB2', 'Eldor Shomurodov', 'Uzbekistán', 'UZB', 'Uzbekistán', 2, 'jugador', 'normal', 861),
(863, 'UZB3', 'Odil Ahmedov', 'Uzbekistán', 'UZB', 'Uzbekistán', 3, 'jugador', 'normal', 862),
(864, 'UZB4', 'Jaloliddin Masharipov', 'Uzbekistán', 'UZB', 'Uzbekistán', 4, 'jugador', 'normal', 863),
(865, 'UZB5', 'Igor Sergeev', 'Uzbekistán', 'UZB', 'Uzbekistán', 5, 'jugador', 'normal', 864),
(866, 'UZB6', 'Otabek Shukurov', 'Uzbekistán', 'UZB', 'Uzbekistán', 6, 'jugador', 'normal', 865),
(867, 'UZB7', 'Sanjar Tursunov', 'Uzbekistán', 'UZB', 'Uzbekistán', 7, 'jugador', 'normal', 866),
(868, 'UZB8', 'Azizbek Turgunboev', 'Uzbekistán', 'UZB', 'Uzbekistán', 8, 'jugador', 'normal', 867),
(869, 'UZB9', 'Khojimat Erkinov', 'Uzbekistán', 'UZB', 'Uzbekistán', 9, 'jugador', 'normal', 868),
(870, 'UZB10', 'Abdulla Abdullayev', 'Uzbekistán', 'UZB', 'Uzbekistán', 10, 'jugador', 'shiny', 869),
(871, 'UZB11', 'Jasurbek Yakhshiboev', 'Uzbekistán', 'UZB', 'Uzbekistán', 11, 'jugador', 'normal', 870),
(872, 'UZB12', 'Iskandar Jalilov', 'Uzbekistán', 'UZB', 'Uzbekistán', 12, 'jugador', 'normal', 871),
(873, 'UZB13', 'Foto de equipo', 'Uzbekistán', 'UZB', 'Uzbekistán', 13, 'foto_equipo', 'special', 872),
(874, 'UZB14', 'Utkir Yusupov', 'Uzbekistán', 'UZB', 'Uzbekistán', 14, 'jugador', 'normal', 873),
(875, 'UZB15', 'Akmal Shorakhmedov', 'Uzbekistán', 'UZB', 'Uzbekistán', 15, 'jugador', 'shiny', 874),
(876, 'UZB16', 'Sherzod Nasriddinov', 'Uzbekistán', 'UZB', 'Uzbekistán', 16, 'jugador', 'normal', 875),
(877, 'UZB17', 'Rustam Ashurmatov', 'Uzbekistán', 'UZB', 'Uzbekistán', 17, 'jugador', 'shiny', 876),
(878, 'UZB18', 'Abdulla Qodirov', 'Uzbekistán', 'UZB', 'Uzbekistán', 18, 'jugador', 'normal', 877),
(879, 'UZB19', 'Farrukh Sayfiev', 'Uzbekistán', 'UZB', 'Uzbekistán', 19, 'jugador', 'normal', 878),
(880, 'UZB20', 'Botir Qodirov', 'Uzbekistán', 'UZB', 'Uzbekistán', 20, 'jugador', 'normal', 879),
(881, 'COD1', 'Escudo Rep. Dem. del Congo', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 1, 'escudo', 'shiny', 880),
(882, 'COD2', 'Yoane Wissa', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 2, 'jugador', 'normal', 881),
(883, 'COD3', 'Cédric Bakambu', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 3, 'jugador', 'normal', 882),
(884, 'COD4', 'Chancel Mbemba', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 4, 'jugador', 'normal', 883),
(885, 'COD5', 'Arthur Masuaku', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 5, 'jugador', 'normal', 884),
(886, 'COD6', 'Gaël Kakuta', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 6, 'jugador', 'normal', 885),
(887, 'COD7', 'Theo Bongonda', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 7, 'jugador', 'normal', 886),
(888, 'COD8', 'Miché Mika', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 8, 'jugador', 'normal', 887),
(889, 'COD9', 'Beni Baningime', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 9, 'jugador', 'normal', 888),
(890, 'COD10', 'Edo Kayembe', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 10, 'jugador', 'shiny', 889),
(891, 'COD11', 'Dieumerci Mbokani', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 11, 'jugador', 'normal', 890),
(892, 'COD12', 'Fabrice N''Sakala', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 12, 'jugador', 'normal', 891),
(893, 'COD13', 'Foto de equipo', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 13, 'foto_equipo', 'special', 892),
(894, 'COD14', 'Marcel Tisserand', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 14, 'jugador', 'normal', 893),
(895, 'COD15', 'Merveille Bokadi', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 15, 'jugador', 'shiny', 894),
(896, 'COD16', 'Paul-José Mpoku', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 16, 'jugador', 'normal', 895),
(897, 'COD17', 'Silas Katompa Mvumpa', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 17, 'jugador', 'shiny', 896),
(898, 'COD18', 'Falaye Sacko', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 18, 'jugador', 'normal', 897),
(899, 'COD19', 'Héritier Luvumbu', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 19, 'jugador', 'normal', 898),
(900, 'COD20', 'Joël Kiassumbua', 'Rep. Dem. del Congo', 'COD', 'Rep. Dem. del Congo', 20, 'jugador', 'normal', 899),
(901, 'ENG1', 'Escudo Inglaterra', 'Inglaterra', 'ENG', 'Inglaterra', 1, 'escudo', 'shiny', 900),
(902, 'ENG2', 'Jordan Pickford', 'Inglaterra', 'ENG', 'Inglaterra', 2, 'jugador', 'normal', 901),
(903, 'ENG3', 'Kyle Walker', 'Inglaterra', 'ENG', 'Inglaterra', 3, 'jugador', 'normal', 902),
(904, 'ENG4', 'John Stones', 'Inglaterra', 'ENG', 'Inglaterra', 4, 'jugador', 'normal', 903),
(905, 'ENG5', 'Marc Guéhi', 'Inglaterra', 'ENG', 'Inglaterra', 5, 'jugador', 'normal', 904),
(906, 'ENG6', 'Luke Shaw', 'Inglaterra', 'ENG', 'Inglaterra', 6, 'jugador', 'normal', 905),
(907, 'ENG7', 'Declan Rice', 'Inglaterra', 'ENG', 'Inglaterra', 7, 'jugador', 'normal', 906),
(908, 'ENG8', 'Jude Bellingham', 'Inglaterra', 'ENG', 'Inglaterra', 8, 'jugador', 'normal', 907),
(909, 'ENG9', 'Phil Foden', 'Inglaterra', 'ENG', 'Inglaterra', 9, 'jugador', 'normal', 908),
(910, 'ENG10', 'Bukayo Saka', 'Inglaterra', 'ENG', 'Inglaterra', 10, 'jugador', 'shiny', 909),
(911, 'ENG11', 'Harry Kane', 'Inglaterra', 'ENG', 'Inglaterra', 11, 'jugador', 'normal', 910),
(912, 'ENG12', 'Raheem Sterling', 'Inglaterra', 'ENG', 'Inglaterra', 12, 'jugador', 'normal', 911),
(913, 'ENG13', 'Foto de equipo', 'Inglaterra', 'ENG', 'Inglaterra', 13, 'foto_equipo', 'special', 912),
(914, 'ENG14', 'Ollie Watkins', 'Inglaterra', 'ENG', 'Inglaterra', 14, 'jugador', 'normal', 913),
(915, 'ENG15', 'Cole Palmer', 'Inglaterra', 'ENG', 'Inglaterra', 15, 'jugador', 'shiny', 914),
(916, 'ENG16', 'Anthony Gordon', 'Inglaterra', 'ENG', 'Inglaterra', 16, 'jugador', 'normal', 915),
(917, 'ENG17', 'Kobbie Mainoo', 'Inglaterra', 'ENG', 'Inglaterra', 17, 'jugador', 'shiny', 916),
(918, 'ENG18', 'Trent Alexander-Arnold', 'Inglaterra', 'ENG', 'Inglaterra', 18, 'jugador', 'normal', 917),
(919, 'ENG19', 'Conor Gallagher', 'Inglaterra', 'ENG', 'Inglaterra', 19, 'jugador', 'normal', 918),
(920, 'ENG20', 'Ivan Toney', 'Inglaterra', 'ENG', 'Inglaterra', 20, 'jugador', 'normal', 919),
(921, 'CRO1', 'Escudo Croacia', 'Croacia', 'CRO', 'Croacia', 1, 'escudo', 'shiny', 920),
(922, 'CRO2', 'Dominik Livaković', 'Croacia', 'CRO', 'Croacia', 2, 'jugador', 'normal', 921),
(923, 'CRO3', 'Josip Šutalo', 'Croacia', 'CRO', 'Croacia', 3, 'jugador', 'normal', 922),
(924, 'CRO4', 'Joško Gvardiol', 'Croacia', 'CRO', 'Croacia', 4, 'jugador', 'normal', 923),
(925, 'CRO5', 'Dejan Lovren', 'Croacia', 'CRO', 'Croacia', 5, 'jugador', 'normal', 924),
(926, 'CRO6', 'Borna Sosa', 'Croacia', 'CRO', 'Croacia', 6, 'jugador', 'normal', 925),
(927, 'CRO7', 'Luka Modrić', 'Croacia', 'CRO', 'Croacia', 7, 'jugador', 'normal', 926),
(928, 'CRO8', 'Marcelo Brozović', 'Croacia', 'CRO', 'Croacia', 8, 'jugador', 'normal', 927),
(929, 'CRO9', 'Mateo Kovačić', 'Croacia', 'CRO', 'Croacia', 9, 'jugador', 'normal', 928),
(930, 'CRO10', 'Ivan Perišić', 'Croacia', 'CRO', 'Croacia', 10, 'jugador', 'shiny', 929),
(931, 'CRO11', 'Bruno Petković', 'Croacia', 'CRO', 'Croacia', 11, 'jugador', 'normal', 930),
(932, 'CRO12', 'Marko Livaja', 'Croacia', 'CRO', 'Croacia', 12, 'jugador', 'normal', 931),
(933, 'CRO13', 'Foto de equipo', 'Croacia', 'CRO', 'Croacia', 13, 'foto_equipo', 'special', 932),
(934, 'CRO14', 'Mario Pašalić', 'Croacia', 'CRO', 'Croacia', 14, 'jugador', 'normal', 933),
(935, 'CRO15', 'Lovro Majer', 'Croacia', 'CRO', 'Croacia', 15, 'jugador', 'shiny', 934),
(936, 'CRO16', 'Ante Budimir', 'Croacia', 'CRO', 'Croacia', 16, 'jugador', 'normal', 935),
(937, 'CRO17', 'Nikola Vlašić', 'Croacia', 'CRO', 'Croacia', 17, 'jugador', 'shiny', 936),
(938, 'CRO18', 'Josip Juranović', 'Croacia', 'CRO', 'Croacia', 18, 'jugador', 'normal', 937),
(939, 'CRO19', 'Martin Erlić', 'Croacia', 'CRO', 'Croacia', 19, 'jugador', 'normal', 938),
(940, 'CRO20', 'Duje Ćaleta-Car', 'Croacia', 'CRO', 'Croacia', 20, 'jugador', 'normal', 939),
(941, 'PAN1', 'Escudo Panamá', 'Panamá', 'PAN', 'Panamá', 1, 'escudo', 'shiny', 940),
(942, 'PAN2', 'Aníbal Godoy', 'Panamá', 'PAN', 'Panamá', 2, 'jugador', 'normal', 941),
(943, 'PAN3', 'Michael Murillo', 'Panamá', 'PAN', 'Panamá', 3, 'jugador', 'normal', 942),
(944, 'PAN4', 'Adalberto Carrasquilla', 'Panamá', 'PAN', 'Panamá', 4, 'jugador', 'normal', 943),
(945, 'PAN5', 'José Fajardo', 'Panamá', 'PAN', 'Panamá', 5, 'jugador', 'normal', 944),
(946, 'PAN6', 'Ismael Díaz', 'Panamá', 'PAN', 'Panamá', 6, 'jugador', 'normal', 945),
(947, 'PAN7', 'Rómulo Hurtado', 'Panamá', 'PAN', 'Panamá', 7, 'jugador', 'normal', 946),
(948, 'PAN8', 'César Blackman', 'Panamá', 'PAN', 'Panamá', 8, 'jugador', 'normal', 947),
(949, 'PAN9', 'Fidel Escobar', 'Panamá', 'PAN', 'Panamá', 9, 'jugador', 'normal', 948),
(950, 'PAN10', 'Omar Browne', 'Panamá', 'PAN', 'Panamá', 10, 'jugador', 'shiny', 949),
(951, 'PAN11', 'José Luis Rodríguez', 'Panamá', 'PAN', 'Panamá', 11, 'jugador', 'normal', 950),
(952, 'PAN12', 'Harold Cummings', 'Panamá', 'PAN', 'Panamá', 12, 'jugador', 'normal', 951),
(953, 'PAN13', 'Foto de equipo', 'Panamá', 'PAN', 'Panamá', 13, 'foto_equipo', 'special', 952),
(954, 'PAN14', 'Luis Mejía', 'Panamá', 'PAN', 'Panamá', 14, 'jugador', 'normal', 953),
(955, 'PAN15', 'Eric Davis', 'Panamá', 'PAN', 'Panamá', 15, 'jugador', 'shiny', 954),
(956, 'PAN16', 'Jorge Gómez', 'Panamá', 'PAN', 'Panamá', 16, 'jugador', 'normal', 955),
(957, 'PAN17', 'Alberto Quintero', 'Panamá', 'PAN', 'Panamá', 17, 'jugador', 'shiny', 956),
(958, 'PAN18', 'Ricardo Ávila', 'Panamá', 'PAN', 'Panamá', 18, 'jugador', 'normal', 957),
(959, 'PAN19', 'Edgar Bárcenas', 'Panamá', 'PAN', 'Panamá', 19, 'jugador', 'normal', 958),
(960, 'PAN20', 'Jorge Herrera', 'Panamá', 'PAN', 'Panamá', 20, 'jugador', 'normal', 959),
(961, 'GHA1', 'Escudo Ghana', 'Ghana', 'GHA', 'Ghana', 1, 'escudo', 'shiny', 960),
(962, 'GHA2', 'Thomas Partey', 'Ghana', 'GHA', 'Ghana', 2, 'jugador', 'normal', 961),
(963, 'GHA3', 'Mohammed Kudus', 'Ghana', 'GHA', 'Ghana', 3, 'jugador', 'normal', 962),
(964, 'GHA4', 'Jordan Ayew', 'Ghana', 'GHA', 'Ghana', 4, 'jugador', 'normal', 963),
(965, 'GHA5', 'André Ayew', 'Ghana', 'GHA', 'Ghana', 5, 'jugador', 'normal', 964),
(966, 'GHA6', 'Daniel Amartey', 'Ghana', 'GHA', 'Ghana', 6, 'jugador', 'normal', 965),
(967, 'GHA7', 'Alexander Djiku', 'Ghana', 'GHA', 'Ghana', 7, 'jugador', 'normal', 966),
(968, 'GHA8', 'Salisu Abdul', 'Ghana', 'GHA', 'Ghana', 8, 'jugador', 'normal', 967),
(969, 'GHA9', 'Kamaldeen Sulemana', 'Ghana', 'GHA', 'Ghana', 9, 'jugador', 'normal', 968),
(970, 'GHA10', 'Inaki Williams', 'Ghana', 'GHA', 'Ghana', 10, 'jugador', 'shiny', 969),
(971, 'GHA11', 'Antoine Semenyo', 'Ghana', 'GHA', 'Ghana', 11, 'jugador', 'normal', 970),
(972, 'GHA12', 'Lawrence Ati-Zigi', 'Ghana', 'GHA', 'Ghana', 12, 'jugador', 'normal', 971),
(973, 'GHA13', 'Foto de equipo', 'Ghana', 'GHA', 'Ghana', 13, 'foto_equipo', 'special', 972),
(974, 'GHA14', 'Ernest Nuamah', 'Ghana', 'GHA', 'Ghana', 14, 'jugador', 'normal', 973),
(975, 'GHA15', 'Osman Bukari', 'Ghana', 'GHA', 'Ghana', 15, 'jugador', 'shiny', 974),
(976, 'GHA16', 'Joseph Paintsil', 'Ghana', 'GHA', 'Ghana', 16, 'jugador', 'normal', 975),
(977, 'GHA17', 'Alidu Seidu', 'Ghana', 'GHA', 'Ghana', 17, 'jugador', 'shiny', 976),
(978, 'GHA18', 'Baba Rahman', 'Ghana', 'GHA', 'Ghana', 18, 'jugador', 'normal', 977),
(979, 'GHA19', 'Abdul Fatawu', 'Ghana', 'GHA', 'Ghana', 19, 'jugador', 'normal', 978),
(980, 'GHA20', 'Ibrahim Salisu', 'Ghana', 'GHA', 'Ghana', 20, 'jugador', 'normal', 979),
(981, 'COC1', 'Lamine Yamal', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 1, 'coca_cola', 'special', 980),
(982, 'COC2', 'Joshua Kimmich', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 2, 'coca_cola', 'special', 981),
(983, 'COC3', 'Virgil van Dijk', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 3, 'coca_cola', 'special', 982),
(984, 'COC4', 'Antonee Robinson', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 4, 'coca_cola', 'special', 983),
(985, 'COC5', 'Alphonso Davies', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 5, 'coca_cola', 'special', 984),
(986, 'COC6', 'Lautaro Martínez', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 6, 'coca_cola', 'special', 985),
(987, 'COC7', 'Harry Kane', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 7, 'coca_cola', 'special', 986),
(988, 'COC8', 'Edson Álvarez', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 8, 'coca_cola', 'special', 987),
(989, 'COC9', 'Weston McKennie', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 9, 'coca_cola', 'special', 988),
(990, 'COC10', 'Jefferson Lerma', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 10, 'coca_cola', 'special', 989),
(991, 'COC11', 'Santiago Giménez', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 11, 'coca_cola', 'special', 990),
(992, 'COC12', 'Gabriel Magalhães', 'Coca-Cola x Panini', 'COC', 'Coca-Cola x Panini', 12, 'coca_cola', 'special', 991)
ON CONFLICT (number) DO UPDATE SET
  code = EXCLUDED.code, name = EXCLUDED.name, section = EXCLUDED.section,
  team_code = EXCLUDED.team_code, team_name = EXCLUDED.team_name,
  team_slot = EXCLUDED.team_slot, sticker_kind = EXCLUDED.sticker_kind,
  sticker_type = EXCLUDED.sticker_type, display_order = EXCLUDED.display_order;
