INSERT INTO public.stickers (number, code, name, section, team_code, team_name, team_slot, sticker_kind, sticker_type, display_order) VALUES
(1, 'FWC1', 'Emblema oficial', 'FWC', 'FWC', 'FIFA World Cup', 1, 'fwc', 'special', 0),
(2, 'FWC2', 'Trofeo FIFA', 'FWC', 'FWC', 'FIFA World Cup', 2, 'fwc', 'shiny', 1),
(3, 'FWC3', 'Mascota del torneo', 'FWC', 'FWC', 'FIFA World Cup', 3, 'fwc', 'normal', 2),
(4, 'FWC4', 'Póster del Mundial', 'FWC', 'FWC', 'FIFA World Cup', 4, 'fwc', 'normal', 3),
(5, 'FWC5', 'Historia FWC 1', 'FWC', 'FWC', 'FIFA World Cup', 5, 'fwc', 'normal', 4),
(6, 'FWC6', 'Historia FWC 2', 'FWC', 'FWC', 'FIFA World Cup', 6, 'fwc', 'normal', 5),
(7, 'FWC7', 'México sede', 'FWC', 'FWC', 'FIFA World Cup', 7, 'fwc', 'shiny', 6),
(8, 'FWC8', 'Estadio Ciudad de México', 'FWC', 'FWC', 'FIFA World Cup', 8, 'fwc', 'normal', 7),
(9, 'FWC9', 'Estadio Guadalajara', 'FWC', 'FWC', 'FIFA World Cup', 9, 'fwc', 'normal', 8),
(10, 'FWC10', 'Estadio Monterrey', 'FWC', 'FWC', 'FIFA World Cup', 10, 'fwc', 'normal', 9),
(11, 'FWC11', 'USA sede', 'FWC', 'FWC', 'FIFA World Cup', 11, 'fwc', 'normal', 10),
(12, 'FWC12', 'Canadá sede', 'FWC', 'FWC', 'FIFA World Cup', 12, 'fwc', 'normal', 11),
(13, 'FWC13', 'FWC Leyenda 1', 'FWC', 'FWC', 'FIFA World Cup', 13, 'fwc', 'shiny', 12),
(14, 'FWC14', 'FWC Leyenda 2', 'FWC', 'FWC', 'FIFA World Cup', 14, 'fwc', 'normal', 13),
(15, 'FWC15', 'FWC Leyenda 3', 'FWC', 'FWC', 'FIFA World Cup', 15, 'fwc', 'normal', 14),
(16, 'FWC16', 'FWC Leyenda 4', 'FWC', 'FWC', 'FIFA World Cup', 16, 'fwc', 'special', 15),
(17, 'FWC17', 'FWC Leyenda 5', 'FWC', 'FWC', 'FIFA World Cup', 17, 'fwc', 'normal', 16),
(18, 'FWC18', 'FWC Leyenda 6', 'FWC', 'FWC', 'FIFA World Cup', 18, 'fwc', 'normal', 17),
(19, 'FWC19', 'FWC Leyenda 7', 'FWC', 'FWC', 'FIFA World Cup', 19, 'fwc', 'shiny', 18),
(20, 'FWC20', 'FWC Leyenda 8', 'FWC', 'FWC', 'FIFA World Cup', 20, 'fwc', 'normal', 19),
(21, 'MEX1', 'Escudo México', 'México', 'MEX', 'México', 1, 'escudo', 'shiny', 20),
(22, 'MEX2', 'Luis Malagón', 'México', 'MEX', 'México', 2, 'jugador', 'normal', 21),
(23, 'MEX3', 'Johan Vásquez', 'México', 'MEX', 'México', 3, 'jugador', 'normal', 22),
(24, 'MEX4', 'Jorge Sánchez', 'México', 'MEX', 'México', 4, 'jugador', 'normal', 23),
(25, 'MEX5', 'César Montes', 'México', 'MEX', 'México', 5, 'jugador', 'normal', 24),
(26, 'MEX6', 'Jesús Gallardo', 'México', 'MEX', 'México', 6, 'jugador', 'normal', 25),
(27, 'MEX7', 'Israel Reyes', 'México', 'MEX', 'México', 7, 'jugador', 'normal', 26),
(28, 'MEX8', 'Diego Laínez', 'México', 'MEX', 'México', 8, 'jugador', 'normal', 27),
(29, 'MEX9', 'Carlos Rodríguez', 'México', 'MEX', 'México', 9, 'jugador', 'normal', 28),
(30, 'MEX10', 'Edson Álvarez', 'México', 'MEX', 'México', 10, 'jugador', 'shiny', 29),
(31, 'MEX11', 'Orbelín Pineda', 'México', 'MEX', 'México', 11, 'jugador', 'normal', 30),
(32, 'MEX12', 'Marcel Ruiz', 'México', 'MEX', 'México', 12, 'jugador', 'normal', 31),
(33, 'MEX13', 'Foto de equipo', 'México', 'MEX', 'México', 13, 'foto_equipo', 'special', 32),
(34, 'MEX14', 'Érick Sánchez', 'México', 'MEX', 'México', 14, 'jugador', 'normal', 33),
(35, 'MEX15', 'Hirving Lozano', 'México', 'MEX', 'México', 15, 'jugador', 'shiny', 34),
(36, 'MEX16', 'Santiago Giménez', 'México', 'MEX', 'México', 16, 'jugador', 'normal', 35),
(37, 'MEX17', 'Raúl Jiménez', 'México', 'MEX', 'México', 17, 'jugador', 'shiny', 36),
(38, 'MEX18', 'Alexis Vega', 'México', 'MEX', 'México', 18, 'jugador', 'normal', 37),
(39, 'MEX19', 'Roberto Alvarado', 'México', 'MEX', 'México', 19, 'jugador', 'normal', 38),
(40, 'MEX20', 'César Huerta', 'México', 'MEX', 'México', 20, 'jugador', 'normal', 39),
(41, 'RSA1', 'Escudo Sudáfrica', 'Sudáfrica', 'RSA', 'Sudáfrica', 1, 'escudo', 'shiny', 40),
(42, 'RSA2', 'Ronwen Williams', 'Sudáfrica', 'RSA', 'Sudáfrica', 2, 'jugador', 'normal', 41),
(43, 'RSA3', 'Grant Kekana', 'Sudáfrica', 'RSA', 'Sudáfrica', 3, 'jugador', 'normal', 42),
(44, 'RSA4', 'Teboho Mokoena', 'Sudáfrica', 'RSA', 'Sudáfrica', 4, 'jugador', 'normal', 43),
(45, 'RSA5', 'Khuliso Mudau', 'Sudáfrica', 'RSA', 'Sudáfrica', 5, 'jugador', 'normal', 44),
(46, 'RSA6', 'Mothobi Mvala', 'Sudáfrica', 'RSA', 'Sudáfrica', 6, 'jugador', 'normal', 45),
(47, 'RSA7', 'Teboho Mokwena', 'Sudáfrica', 'RSA', 'Sudáfrica', 7, 'jugador', 'normal', 46),
(48, 'RSA8', 'Sphelele Mkhulise', 'Sudáfrica', 'RSA', 'Sudáfrica', 8, 'jugador', 'normal', 47),
(49, 'RSA9', 'Thapelo Maseko', 'Sudáfrica', 'RSA', 'Sudáfrica', 9, 'jugador', 'normal', 48),
(50, 'RSA10', 'Sphelele Ntubeni', 'Sudáfrica', 'RSA', 'Sudáfrica', 10, 'jugador', 'shiny', 49),
(51, 'RSA11', 'Themba Zwane', 'Sudáfrica', 'RSA', 'Sudáfrica', 11, 'jugador', 'normal', 50),
(52, 'RSA12', 'Percy Tau', 'Sudáfrica', 'RSA', 'Sudáfrica', 12, 'jugador', 'normal', 51),
(53, 'RSA13', 'Foto de equipo', 'Sudáfrica', 'RSA', 'Sudáfrica', 13, 'foto_equipo', 'special', 52),
(54, 'RSA14', 'Evidence Makgopa', 'Sudáfrica', 'RSA', 'Sudáfrica', 14, 'jugador', 'normal', 53),
(55, 'RSA15', 'Zakhele Lepasa', 'Sudáfrica', 'RSA', 'Sudáfrica', 15, 'jugador', 'shiny', 54),
(56, 'RSA16', 'Tebogo Maseko', 'Sudáfrica', 'RSA', 'Sudáfrica', 16, 'jugador', 'normal', 55),
(57, 'RSA17', 'Mihlali Mayambela', 'Sudáfrica', 'RSA', 'Sudáfrica', 17, 'jugador', 'shiny', 56),
(58, 'RSA18', 'Oswin Appollis', 'Sudáfrica', 'RSA', 'Sudáfrica', 18, 'jugador', 'normal', 57),
(59, 'RSA19', 'Thapelo Leshabane', 'Sudáfrica', 'RSA', 'Sudáfrica', 19, 'jugador', 'normal', 58),
(60, 'RSA20', 'Iqraam Rayners', 'Sudáfrica', 'RSA', 'Sudáfrica', 20, 'jugador', 'normal', 59),
(61, 'USA1', 'Escudo Estados Unidos', 'Estados Unidos', 'USA', 'Estados Unidos', 1, 'escudo', 'shiny', 60),
(62, 'USA2', 'Matt Turner', 'Estados Unidos', 'USA', 'Estados Unidos', 2, 'jugador', 'normal', 61),
(63, 'USA3', 'Sergiño Dest', 'Estados Unidos', 'USA', 'Estados Unidos', 3, 'jugador', 'normal', 62),
(64, 'USA4', 'Chris Richards', 'Estados Unidos', 'USA', 'Estados Unidos', 4, 'jugador', 'normal', 63),
(65, 'USA5', 'Antonee Robinson', 'Estados Unidos', 'USA', 'Estados Unidos', 5, 'jugador', 'normal', 64),
(66, 'USA6', 'Walker Zimmerman', 'Estados Unidos', 'USA', 'Estados Unidos', 6, 'jugador', 'normal', 65),
(67, 'USA7', 'Tyler Adams', 'Estados Unidos', 'USA', 'Estados Unidos', 7, 'jugador', 'normal', 66),
(68, 'USA8', 'Yunus Musah', 'Estados Unidos', 'USA', 'Estados Unidos', 8, 'jugador', 'normal', 67),
(69, 'USA9', 'Weston McKennie', 'Estados Unidos', 'USA', 'Estados Unidos', 9, 'jugador', 'normal', 68),
(70, 'USA10', 'Gio Reyna', 'Estados Unidos', 'USA', 'Estados Unidos', 10, 'jugador', 'shiny', 69),
(71, 'USA11', 'Christian Pulisic', 'Estados Unidos', 'USA', 'Estados Unidos', 11, 'jugador', 'normal', 70),
(72, 'USA12', 'Ricardo Pepi', 'Estados Unidos', 'USA', 'Estados Unidos', 12, 'jugador', 'normal', 71),
(73, 'USA13', 'Foto de equipo', 'Estados Unidos', 'USA', 'Estados Unidos', 13, 'foto_equipo', 'special', 72),
(74, 'USA14', 'Folarin Balogun', 'Estados Unidos', 'USA', 'Estados Unidos', 14, 'jugador', 'normal', 73),
(75, 'USA15', 'Haji Wright', 'Estados Unidos', 'USA', 'Estados Unidos', 15, 'jugador', 'shiny', 74),
(76, 'USA16', 'Josh Sargent', 'Estados Unidos', 'USA', 'Estados Unidos', 16, 'jugador', 'normal', 75),
(77, 'USA17', 'Brenden Aaronson', 'Estados Unidos', 'USA', 'Estados Unidos', 17, 'jugador', 'shiny', 76),
(78, 'USA18', 'Tim Weah', 'Estados Unidos', 'USA', 'Estados Unidos', 18, 'jugador', 'normal', 77),
(79, 'USA19', 'Johnny Cardoso', 'Estados Unidos', 'USA', 'Estados Unidos', 19, 'jugador', 'normal', 78),
(80, 'USA20', 'Malik Tillman', 'Estados Unidos', 'USA', 'Estados Unidos', 20, 'jugador', 'normal', 79),
(81, 'CAN1', 'Escudo Canadá', 'Canadá', 'CAN', 'Canadá', 1, 'escudo', 'shiny', 80),
(82, 'CAN2', 'Maxime Crépeau', 'Canadá', 'CAN', 'Canadá', 2, 'jugador', 'normal', 81),
(83, 'CAN3', 'Alphonso Davies', 'Canadá', 'CAN', 'Canadá', 3, 'jugador', 'normal', 82),
(84, 'CAN4', 'Steven Vitoria', 'Canadá', 'CAN', 'Canadá', 4, 'jugador', 'normal', 83),
(85, 'CAN5', 'Sam Adekugbe', 'Canadá', 'CAN', 'Canadá', 5, 'jugador', 'normal', 84),
(86, 'CAN6', 'Derek Cornelius', 'Canadá', 'CAN', 'Canadá', 6, 'jugador', 'normal', 85),
(87, 'CAN7', 'Richie Laryea', 'Canadá', 'CAN', 'Canadá', 7, 'jugador', 'normal', 86),
(88, 'CAN8', 'Sam Piette', 'Canadá', 'CAN', 'Canadá', 8, 'jugador', 'normal', 87),
(89, 'CAN9', 'Stephen Eustáquio', 'Canadá', 'CAN', 'Canadá', 9, 'jugador', 'normal', 88),
(90, 'CAN10', 'Jonathan David', 'Canadá', 'CAN', 'Canadá', 10, 'jugador', 'shiny', 89),
(91, 'CAN11', 'Liam Millar', 'Canadá', 'CAN', 'Canadá', 11, 'jugador', 'normal', 90),
(92, 'CAN12', 'Tajon Buchanan', 'Canadá', 'CAN', 'Canadá', 12, 'jugador', 'normal', 91),
(93, 'CAN13', 'Foto de equipo', 'Canadá', 'CAN', 'Canadá', 13, 'foto_equipo', 'special', 92),
(94, 'CAN14', 'Cyle Larin', 'Canadá', 'CAN', 'Canadá', 14, 'jugador', 'normal', 93),
(95, 'CAN15', 'Jacob Shaffelburg', 'Canadá', 'CAN', 'Canadá', 15, 'jugador', 'shiny', 94),
(96, 'CAN16', 'Ismaël Koné', 'Canadá', 'CAN', 'Canadá', 16, 'jugador', 'normal', 95),
(97, 'CAN17', 'Junior Hoilett', 'Canadá', 'CAN', 'Canadá', 17, 'jugador', 'shiny', 96),
(98, 'CAN18', 'Lucas Cavallini', 'Canadá', 'CAN', 'Canadá', 18, 'jugador', 'normal', 97),
(99, 'CAN19', 'Mark-Anthony Kaye', 'Canadá', 'CAN', 'Canadá', 19, 'jugador', 'normal', 98),
(100, 'CAN20', 'Kamal Miller', 'Canadá', 'CAN', 'Canadá', 20, 'jugador', 'normal', 99),
(101, 'ARG1', 'Escudo Argentina', 'Argentina', 'ARG', 'Argentina', 1, 'escudo', 'shiny', 100),
(102, 'ARG2', 'Emiliano Martínez', 'Argentina', 'ARG', 'Argentina', 2, 'jugador', 'normal', 101),
(103, 'ARG3', 'Cristian Romero', 'Argentina', 'ARG', 'Argentina', 3, 'jugador', 'normal', 102),
(104, 'ARG4', 'Nicolás Otamendi', 'Argentina', 'ARG', 'Argentina', 4, 'jugador', 'normal', 103),
(105, 'ARG5', 'Marcos Acuña', 'Argentina', 'ARG', 'Argentina', 5, 'jugador', 'normal', 104),
(106, 'ARG6', 'Gonzalo Montiel', 'Argentina', 'ARG', 'Argentina', 6, 'jugador', 'normal', 105),
(107, 'ARG7', 'Leandro Pardo', 'Argentina', 'ARG', 'Argentina', 7, 'jugador', 'normal', 106),
(108, 'ARG8', 'Rodrigo De Paul', 'Argentina', 'ARG', 'Argentina', 8, 'jugador', 'normal', 107),
(109, 'ARG9', 'Enzo Fernández', 'Argentina', 'ARG', 'Argentina', 9, 'jugador', 'normal', 108),
(110, 'ARG10', 'Alexis Mac Allister', 'Argentina', 'ARG', 'Argentina', 10, 'jugador', 'shiny', 109),
(111, 'ARG11', 'Ángel Di María', 'Argentina', 'ARG', 'Argentina', 11, 'jugador', 'normal', 110),
(112, 'ARG12', 'Lautaro Martínez', 'Argentina', 'ARG', 'Argentina', 12, 'jugador', 'normal', 111),
(113, 'ARG13', 'Foto de equipo', 'Argentina', 'ARG', 'Argentina', 13, 'foto_equipo', 'special', 112),
(114, 'ARG14', 'Julián Álvarez', 'Argentina', 'ARG', 'Argentina', 14, 'jugador', 'normal', 113),
(115, 'ARG15', 'Nicolás González', 'Argentina', 'ARG', 'Argentina', 15, 'jugador', 'shiny', 114),
(116, 'ARG16', 'Paulo Dybala', 'Argentina', 'ARG', 'Argentina', 16, 'jugador', 'normal', 115),
(117, 'ARG17', 'Giovani Lo Celso', 'Argentina', 'ARG', 'Argentina', 17, 'jugador', 'shiny', 116),
(118, 'ARG18', 'Lisandro Martínez', 'Argentina', 'ARG', 'Argentina', 18, 'jugador', 'normal', 117),
(119, 'ARG19', 'Exequiel Palacios', 'Argentina', 'ARG', 'Argentina', 19, 'jugador', 'normal', 118),
(120, 'ARG20', 'Germán Pezzella', 'Argentina', 'ARG', 'Argentina', 20, 'jugador', 'normal', 119),
(121, 'BRA1', 'Escudo Brasil', 'Brasil', 'BRA', 'Brasil', 1, 'escudo', 'shiny', 120),
(122, 'BRA2', 'Alisson', 'Brasil', 'BRA', 'Brasil', 2, 'jugador', 'normal', 121),
(123, 'BRA3', 'Danilo', 'Brasil', 'BRA', 'Brasil', 3, 'jugador', 'normal', 122),
(124, 'BRA4', 'Marquinhos', 'Brasil', 'BRA', 'Brasil', 4, 'jugador', 'normal', 123),
(125, 'BRA5', 'Gabriel Magalhães', 'Brasil', 'BRA', 'Brasil', 5, 'jugador', 'normal', 124),
(126, 'BRA6', 'Guimarães', 'Brasil', 'BRA', 'Brasil', 6, 'jugador', 'normal', 125),
(127, 'BRA7', 'Casemiro', 'Brasil', 'BRA', 'Brasil', 7, 'jugador', 'normal', 126),
(128, 'BRA8', 'Bruno Guimarães', 'Brasil', 'BRA', 'Brasil', 8, 'jugador', 'normal', 127),
(129, 'BRA9', 'Paquetá', 'Brasil', 'BRA', 'Brasil', 9, 'jugador', 'normal', 128),
(130, 'BRA10', 'Rodrygo', 'Brasil', 'BRA', 'Brasil', 10, 'jugador', 'shiny', 129),
(131, 'BRA11', 'Vinícius Jr', 'Brasil', 'BRA', 'Brasil', 11, 'jugador', 'normal', 130),
(132, 'BRA12', 'Raphinha', 'Brasil', 'BRA', 'Brasil', 12, 'jugador', 'normal', 131),
(133, 'BRA13', 'Foto de equipo', 'Brasil', 'BRA', 'Brasil', 13, 'foto_equipo', 'special', 132),
(134, 'BRA14', 'Neymar', 'Brasil', 'BRA', 'Brasil', 14, 'jugador', 'normal', 133),
(135, 'BRA15', 'Richarlison', 'Brasil', 'BRA', 'Brasil', 15, 'jugador', 'shiny', 134),
(136, 'BRA16', 'Endrick', 'Brasil', 'BRA', 'Brasil', 16, 'jugador', 'normal', 135),
(137, 'BRA17', 'Martinelli', 'Brasil', 'BRA', 'Brasil', 17, 'jugador', 'shiny', 136),
(138, 'BRA18', 'Bremer', 'Brasil', 'BRA', 'Brasil', 18, 'jugador', 'normal', 137),
(139, 'BRA19', 'Wesley', 'Brasil', 'BRA', 'Brasil', 19, 'jugador', 'normal', 138),
(140, 'BRA20', 'Bento', 'Brasil', 'BRA', 'Brasil', 20, 'jugador', 'normal', 139)
ON CONFLICT (number) DO UPDATE SET
  code = EXCLUDED.code, name = EXCLUDED.name, section = EXCLUDED.section,
  team_code = EXCLUDED.team_code, team_name = EXCLUDED.team_name,
  team_slot = EXCLUDED.team_slot, sticker_kind = EXCLUDED.sticker_kind,
  sticker_type = EXCLUDED.sticker_type, display_order = EXCLUDED.display_order;
