/** Agrupa selecciones como en el álbum Panini (orden de lectura natural). */
export const TEAM_SECTIONS = [
  { id: "fwc", label: "FWC", title: "FIFA World Cup", icon: "🏆" },
  { id: "hosts", label: "Sedes", title: "Anfitriones", icon: "🏟️" },
  { id: "america", label: "América", title: "CONMEBOL & CONCACAF", icon: "🌎" },
  { id: "europe", label: "Europa", title: "UEFA", icon: "🇪🇺" },
  { id: "africa", label: "África", title: "CAF", icon: "🌍" },
  { id: "asia", label: "Asia & Oceanía", title: "AFC & OFC", icon: "🌏" },
];

export const TEAM_TO_SECTION = {
  FWC: "fwc",
  MEX: "hosts",
  USA: "hosts",
  CAN: "hosts",
  ARG: "america",
  BRA: "america",
  COL: "america",
  ECU: "america",
  PAR: "america",
  URU: "america",
  PAN: "america",
  HAI: "america",
  CUW: "america",
  GER: "europe",
  ENG: "europe",
  FRA: "europe",
  ESP: "europe",
  POR: "europe",
  NED: "europe",
  BEL: "europe",
  CRO: "europe",
  AUT: "europe",
  SUI: "europe",
  SCO: "europe",
  NOR: "europe",
  SWE: "europe",
  CZE: "europe",
  BIH: "europe",
  TUR: "europe",
  ALG: "africa",
  RSA: "africa",
  MAR: "africa",
  SEN: "africa",
  EGY: "africa",
  GHA: "africa",
  CIV: "africa",
  COD: "africa",
  CPV: "africa",
  TUN: "africa",
  JPN: "asia",
  KOR: "asia",
  AUS: "asia",
  IRN: "asia",
  KSA: "asia",
  QAT: "asia",
  UZB: "asia",
  IRQ: "asia",
  JOR: "asia",
  NZL: "asia",
};

export function sectionForTeam(code) {
  return TEAM_TO_SECTION[code] || "america";
}
